### ISSUE TITLE
reify method args named _ become namespace-qualified inside syntaxquote

### ISSUE THREAD

**Issue by jafingerhut** [ztellman/aleph#124]
In particular, in the macro channel-handler here: https://github.com/ztellman/aleph/blob/0.4.0/src/aleph/netty.clj#L277-L342

Those arguments are all ignored, so I don't see an aleph bug here at all.  It does have the property that tools.analyzer throws an exception when attempting to analyze it, due to the namespace qualifiers.  The current thinking is that this exception in tools.analyzer is a good thing, since such method arguments cannot be used in the body of the method, so it is likely a bug to have them.

**Comment by ztellman** [comment]
Fixed.
