### ISSUE TITLE
Long polling with aleph http client does not wait for response

### ISSUE THREAD

**Issue by reshefm** [ztellman/aleph#133]
I trying lonpolling on the couch db changes feed (http://docs.couchdb.org/en/latest/api/database/changes.html#changes-longpoll) using an aleph http client however the client returns an answer after a few seconds and does not keep waiting.

Using the roughly the call using clj-http works as expected.

I'm using the `:as :stream` option when performing the call on both cases.

**Comment by ztellman** [comment]
What version are you using, and can you provide some code that shows exactly what you're doing?

**Comment by reshefm** [comment]
Thanks for the prompt response!

I'm using version 0.4.0-beta1.

This is the code:
```
(require '[aleph.http :as http])

(def res (http/request {:url "http://localhost:7008/af-apps/_changes?feed=longpoll&style=main_only&heartbeat=10000&since=1600000"
                          :method :get
                          :as :stream}))

(def st (bs/to-string (:body @res)))
```

The response I get is:

```
"{\"results\":[\n\n"
```
Which is as you can see not complete.

**Comment by ztellman** [comment]
It's going to be a little difficult to debug this without access to your `localhost`, but can you give me the output of `curl -v "http://localhost:7008/af-apps/_changes?feed=longpoll&style=main_only&heartbeat=10000&since=1600000"`?

**Comment by reshefm** [comment]
The output is below. It keeps waiting on the connection where every 10 seconds a newline is being sent because of the heartbeat argument.

```
╰─▶ curl -v "http://localhost:7008/af-apps/_changes?feed=longpoll&style=main_only&heartbeat=10000&since=1600000"
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 7008 (#0)
> GET /af-apps/_changes?feed=longpoll&style=main_only&heartbeat=10000&since=1600000 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:7008
> Accept: */*
> 
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
* Server CouchDB/1.2.0 (Erlang OTP/R14B04) is not blacklisted
< Server: CouchDB/1.2.0 (Erlang OTP/R14B04)
< Date: Tue, 20 Jan 2015 20:16:56 GMT
< Content-Type: text/plain; charset=utf-8
< Cache-Control: must-revalidate
< 
{"results":[
```

**Comment by ztellman** [comment]
Okay, I was mostly seeing if the transfer encoding was chunked.  I've done some quick sanity checks, and basic chunked response handling works for me in beta1, so it must be something particular about how CouchDB is responding.  

I'm happy to install CouchDB and try to investigate further.  I've not used it before, can you give me any guidance on what I need to do to reproduce your call?  A particular configuration, or data that needs to be loaded, etc?

**Comment by reshefm** [comment]
Thanks for your help.
My setup is pretty straight forward - nothing special should be configured other than creating a db (`af-apps` in the call I made). Other than that the call I made should reproduce this case.
Please pay attention that the default port for CouchDB is 5984 and not 7008 as I'm using and that I'm using version 1.2.0.

**Comment by ztellman** [comment]
Turns out I was returning the connection to the pool without waiting for the response to terminate, and after ten seconds the connection pool was closing the connection due to "inactivity".  This was an oversight on my part, but probably one that would have taken a while to surface without exactly this sort of test case.  I really appreciate the report, it should work if you target `0.4.0-SNAPSHOT`.

**Comment by reshefm** [comment]
@ztellman Thanks a lot for taking care of it so quickly. I really like the direction Aleph is heading towards along with the Manifold abstractions.

**Comment by ztellman** [comment]
Thanks for the very useful bug report, let me know if you have any other problems.
