### ISSUE TITLE
redirect middleware

### ISSUE THREAD

**Issue by shmish111** [ztellman/aleph#143]
Is there a reason why the [clj-http redirects middleware](https://github.com/dakrone/clj-http/blob/master/src/clj_http/client.clj#L184) hasn't been implemented in Aleph?  I have been working on an implementation, would you be interested in a PR?  I would include it in the `aleph.http.client-middleware` namespace and I also have tests so would these go in `aleph.http.client-middleware-test`?

**Comment by ztellman** [comment]
A version of this was already sitting on my machine, sorry for any wasted effort on your part.  Let me know if you need anything else.
