### ISSUE TITLE
Impossible to override host in HTTP requests

### ISSUE THREAD

**Issue by ddossot** [ztellman/aleph#149]
I need to send a request, say, to `domain1.acme.com` as if I was sending it to `domain2.acme.com` (that's because `acme.com` serves multiple domains but I can't access it directly).

In `curl` or `http-client` I do this by providing a `Host` header that contains `domain2.acme.com`. I've tried the same with Aleph but to no avail.

Is it possible using some sort of override in the request map?

**Comment by ddossot** [comment]
Turns out the server at `domain1.acme.com` honours the `X-Forwarded-Host` header which allows me to reach my goal without needing to override the `Host` header.

Therefore: closing this ticket.

**Comment by ztellman** [comment]
This is a totally reasonable thing to expect, so I added it in.  Thanks for the issue.

**Comment by ddossot** [comment]
Oh wow, great, thanks a lot :bow:
