### ISSUE TITLE
Recommended Routing Library?

### ISSUE THREAD

**Issue by code-ape** [ztellman/aleph#150]
I've seen older examples of aleph.http using Compojure with a structure like:
```Clojure
(start-http-server (wrap-ring-handler app-routes) {:port 8080})
```
Which seems to be clearly outdated since it's using the `start-http-server` command. Is there a recommended / supported routing library for aleph.http? 
[Source of Example](https://github.com/alexkehayias/clojure-aleph-chat/blob/master/project/src/clj/core/main.clj)

**Comment by ztellman** [comment]
The more recent version can be used with existing routing libraries without any additional middleware, as long as you're using normal Ring responses.  There is, however, some amount of work required to make Compojure et al work with websockets and async responses (many routing libraries will try to parse the response for you).

**Comment by ztellman** [comment]
Leaving this issue open until I have the `aleph.examples.http` code complete.

**Comment by ztellman** [comment]
Check out http://ideolalia.com/aleph/literate.html and let me know if you have any further questions.  It's still only a partial set of examples, but should address at least the routing library issue.

**Comment by code-ape** [comment]
Thank you so much! The examples you put up are exactly what I was looking for.

**Comment by tomerweller** [comment]
Also looking for some routing examples but it seems like the above link doesn't work.

**Comment by ztellman** [comment]
It moved to http://aleph.io/aleph/literate.html
