### ISSUE TITLE
Pure TCP client example?

### ISSUE THREAD

**Issue by tgallant** [ztellman/aleph#153]
Hi I am using your library to try to build a client for the [mpd protocol](http://www.musicpd.org/doc/protocol/). I'm following your example tcp code but am having a bit of trouble getting started. I am making a TCP connection on port 6600 to another computer on my network. I need to send commands and recieve the response. `put!` doesn't register any action on the server and `take!` hangs indefinitely. I feel like I'm just missing some fundamental concept. My code is posted below.  Thanks for your time

    (ns mpd.clj
      (:require [clojure.core.async :as async]
                [manifold.deferred :as d]
                [manifold.stream :as s]
                [clojure.edn :as edn]
                [aleph.tcp :as tcp]
                [gloss.core :as gloss]
                [gloss.io :as io]))

    (def protocol
      (gloss/compile-frame
        (gloss/finite-frame :uint32
          (gloss/string :utf-8))
        pr-str
        edn/read-string))

    (defn wrap-duplex-stream
      [protocol s]
      (let [out (s/stream)]
        (s/connect
          (s/map #(io/encode protocol %) out)
          s)
        (s/splice
          out
          (io/decode-stream s protocol))))

    (defn client
      [host port]
      (d/chain (tcp/client {:host host, :port port})
        #(wrap-duplex-stream protocol %)))

    (def c @(client "192.168.1.2" 6600))
    @(s/put! c "status\n") ; returns true
    @(s/take! c)  ; hangs

**Comment by ztellman** [comment]
The MDP protocol seems to just consist of newline-delimited strings, but you're using the example protocol, which is something different.  Notably, the use of `pr-str` in the codec will escape the newline, so the server won't actually ever see the character it's looking for.

I don't have a test server handy, but something like this should work:

```clj
(def protocol (gloss/string :utf-8 :delimiters ["\n"]))
```

Please feel free to reopen the issue if not.

**Comment by tgallant** [comment]
wow that was fast. thanks for your help, that got it working. i'll have to read up more on gloss
