### ISSUE TITLE
Client gets stuck after certain number of redirects

### ISSUE THREAD

**Issue by shmish111** [ztellman/aleph#155]
Since https://github.com/ztellman/aleph/commit/d1036e84eafd5171208832be5760755091f50932

I have a test http server which will redirect from one url to another forever.  Since this commit, if I set max redirects to a number greater than 6 then after 6 redirects the client gets stuck, blocking forever.  Presumably I have run out of threads somewhere and am deadlocked.  I don't understand the code enough to work out how this happens and fix it, sorry :(

**Comment by ztellman** [comment]
Connections are stacking up, rather than being released after each redirect.  Refactoring stuff now, thanks for the report.

**Comment by shmish111** [comment]
I need to study this a bit to try to understand what is going on but am I right in thinking that this means it is not a good idea to have middleware that calls additional http requests?  I have some crawler middleware that would need to make a call to some other url based on the response, would this mean that I would be sucking 2 threads up, the original thread blocking while another does my secondary http call?

**Comment by ztellman** [comment]
If you wrap your middleware around `request`, it wouldn't be an issue.  I'm only doing it this way to minimize the overhead of applying all the middleware layers on each request.  You made a good point, though, so I've made sure that any `:middleware` passed into `request` doesn't have to worry about this either.

Let me know if you have any other questions or concerns.
