### ISSUE TITLE
Extraction of flow ns from aleph

### ISSUE THREAD

**Issue by bts** [ztellman/aleph#156]
Hi Zach,

What do you think about having the instrumented/clojure interface to dirigiste extracted out of aleph? I'd like to use the instrumented executors and pool without having to take on aleph, potemkin, netty, and byte-streams as dependencies.

FWIW I want to create a manifold interface to java.jdbc which works around its synchronous nature with a dirigiste thread pool.

Possible destinations for the code:
* dirigiste: this would add the first clojure code to that project, and manifold as a dependency
* new library. name? manifold-dirigiste, dirigiste-manifold, manifold-pools, dirigiste-clj, clj-dirigiste?

If this is something you'd support, I'd be happy to help however I can.

Thanks,
Brian

**Comment by ztellman** [comment]
I'll give this some thought, but for now just copy/paste the code you want, and add an attribution in the comments.  All totally valid under the MIT license.  Leaving this issue open until I have a stronger opinion on it.

**Comment by bts** [comment]
Thanks

**Comment by ztellman** [comment]
I've extracted the executor stuff into Manifold, but the pool functionality remains in Aleph.  This is probably about as far as I'll take it, but the copy/paste route remains open.
