### ISSUE TITLE
Support :multipart in HTTP Client requests

### ISSUE THREAD

**Issue by spiralman** [ztellman/aleph#159]
I cannot find support for the `:multipart` request parameter in the HTTP client, and my attempts at multipart file uploads fail (the remote end closes the connection, with a very short request length, indicating no body is being sent).

If this is supported, is there any documentation beyond the clj-http docs? Or is it not supported?

**Comment by ztellman** [comment]
It is currently not supported.  I'll take a look at how clj-http handles this.

**Comment by spiralman** [comment]
Thanks.

clj-http handles it by accepting a separate request paramter, `:multipart` instead of `:body`, which is a vector of "parts," each of which is a map containing the properties of the part (name, content (string or file), content type, etc).

I've been looking into implementing it as a middleware (with an eye toward contributing it back), by using Netty's [HttpPostRequestEncoder](http://netty.io/4.0/api/io/netty/handler/codec/http/multipart/HttpPostRequestEncoder.html). I was hoping that I could just set the `Content-Type` header and set the `:body` to a stream that yielded the encoded file data.

The problem is that Netty's encoder works by [modifying a Netty HttpRequest prior to writing it to the channel](https://github.com/netty/netty/blob/master/example/src/main/java/io/netty/example/http/upload/HttpUploadClient.java#L261), but middleware isn't given access to the intermediate HttpRequest object (that I can determine), and can't pass along a Netty HttpRequest.

I'm going to try to spend a little more time trying to find a hook I can use to do the encoding, but I suspect that this will need to be implemented in the core, without bending over backwards.

**Comment by ztellman** [comment]
Sorry that this didn't make the cut for the `0.4.0` release, but I'll be sure to get to it by `0.4.1`.

**Comment by spiralman** [comment]
No problem! I was hoping to take a whack at it myself, but life managed to intervene (as usual). Thanks for the update!

**Comment by martinraison** [comment]
+1

**Comment by malcolmsparks** [comment]
+1 (voting for this issue too, I'd really like it for my tests)

**Comment by keeth** [comment]
+1

**Comment by jjl** [comment]
I'm liable to take a crack at this in the next couple of weeks because one of our soon-to-be-production apps uses aleph for http service and we'd like to use it for clients as well.

**Comment by jjl** [comment]
Okay, I've had an initial go at doing this, see my attempt at https://github.com/jjl/aleph/tree/multipart-support . Doesn't work yet because I haven't figured out what to use for quoted-printable and base64 encoding yet. Any recommendations or comments?

**Comment by ztellman** [comment]
I'm sorry for not responding to this sooner.  For base64, I'd use the implementation in Netty, since that doesn't bring in an extra dependency: http://netty.io/4.0/api/io/netty/handler/codec/base64/Base64.html.  As far as quoted-printable, I think it should be pretty easy to roll our own.  Let me take a look at your code and see what I can do.

**Comment by jjl** [comment]
Okay, I've implemented netty-based base64 encoding on my `multipart-v2` branch and as a standin I've used commons.codec for quoted printable. happy to replace that with something else

https://github.com/jjl/aleph/blob/multipart-v2/src/aleph/http/encoding.clj

**Comment by jjl** [comment]
One thing I'm not too clear on is where the next step of the process is. I've tracked down ring-request->full-netty-request, is this the only spot I need to update?

**Comment by ztellman** [comment]
No, `ring-request->full-netty-request` is only used for websocket interop.  The key part to change is https://github.com/ztellman/aleph/blob/master/src/aleph/http/client.clj#L314.  Let me know if you have other questions.

**Comment by ztellman** [comment]
I brought in your `multipart-v2` branch.  There were a few issues that prevented compilation, so I gather this hasn't been tested at all.  That's fine, but I need to think a bit about how to test the implementation.  If you have any thoughts, let me know.

**Comment by jjl** [comment]
That's right, I'm not looking forward to writing the test because
serialisation tests are never fun. Maybe cowboy (erlang) has some i can
port.

/j

**Comment by ztellman** [comment]
I would assume that we could use the Apache codecs that they use in
clj-http, but I haven't looked at it very closely.

**Comment by solatis** [comment]
I'm might be willing to contribute some time to get multipart functionality working, but I'm curious about the approach to take. I assume that correctness is more important than performance/elegance at this point, so I would probably use Netty or Apache codecs. 

@ztellman if you were to implement this yourself, what approach would you take ?

**Comment by ztellman** [comment]
@solatis an implementation exists in https://github.com/ztellman/aleph/blob/master/src/aleph/http/multipart.clj, but it has no tests.  The remaining work is to validate the implementation and uncomment https://github.com/ztellman/aleph/blob/master/src/aleph/http/client.clj#L317.  If you'd like to take the lead on that, that would be hugely helpful.

**Comment by solatis** [comment]
@ztellman great, I was already wondering whether that code was usable or not. I'll write a test suite for this.

**Comment by solatis** [comment]
@ztellman I've integrated the multipart test suite of clj-http and enabled aleph/http's multipart code, but it appears as if it's pretty broken -- NPEs in multiple places, and I worry whether this approach is the best way to make sure we cover all the corner cases.

I'm tempted to just re-use Netty's existing multipart implementation, given that that will probably give better results more quickly.

**Comment by ztellman** [comment]
If you can use it without having to mess around with the channel pipelines, I'm fine with that.  If you need to integrate it using channel pipelines, I'm tempted to roll our own.

**Comment by solatis** [comment]
I tried fiddling with it for a few hours, but it seems as if Netty's HTTP client requires you to use their entire framework. Given that the logic is not that difficult, I agree with you that rolling our own seems to be the best at this point.

I'll poke at the existing multipart code a bit to see if I can get it to work, or I'll refactor it until it works.

**Comment by JarredLHumphrey** [comment]
+1 we've just made the switch over to aleph from http-kit and this is blocking some desired functionality. Happy to help out w/ this in my spare time if you guys desire!

**Comment by solatis** [comment]
For what it's worth, I'm still planning on fixing the multipart upload, I just ran into some issues and it's taking longer than I anticipated.

**Comment by alexandergunnarson** [comment]
I've also taken a stab at this and the code changes I made to avoid the NPEs, etc. were pretty straightforward but it's still not working properly. I'm using the Amazon Cloud Drive API and trying to upload a very short piece of text as a file, but even though the `ByteBuffer`s seem to be exactly what they need to be in terms of headers, boundaries, and content, Amazon is responding with a 500.

Here's the string (via `(String. (.array buf))`) that `encode-body` is generating, which is both expected from the Ring request and seems to match what Amazon claims to need:
```
----WebKitFormBoundaryb5c8df59e963e970
content-disposition: form-data; name="metadata"
content-type: application/json
content-transfer-encoding: identity

{"name":"Test.txt","parents":["-rl6yZJOTgKY_zvHD44IrQ"],"kind":"FILE"}
----WebKitFormBoundaryb5c8df59e963e970
content-disposition: form-data; name="content"
content-type: application/text
content-transfer-encoding: identity

bshdabsdhjasbdhasjdasdfj218912y7n21cy71n2cy12cn71n2cy81
----WebKitFormBoundaryb5c8df59e963e970
```

Amazon claims to need something like the following (copy-pasted example from [their API docs](https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes)):

```
POST /cdproxy/nodes?localId=testPhoto
HTTP/1.1
Host: content-na.drive.amazonaws.com
Authorization: Bearer
Atza|IQEBLjAsAhReYeezFcFdYzqrFOJGv3EG
 
----WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="metadata"
 
{"name":"fooo.jpg","kind":"FILE"} 
----WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="content";
filename="db5df4870e4e4b6cbf42727fd434701a.jpg"
Content-Type: image/jpeg
 
----WebKitFormBoundaryE19zNvXGzXaLvS5C
```

Not sure what it's complaining about:
```
:headers {... "content-type" "application/vnd.error+json" ...}
:body "{\"message\":\"Internal failure\"}"
:status 500
...
```

If I try to use the built-in clj-http multipart functionality, it always seems to result in a `SerializationException`, and the httpkit multipart functionality doesn't quite work for me either. Strangely, it does work using a custom multipart handler I created based on `org.apache.http.*`. I have to investigate why at some point.

@solatis let me know how your implementation's going. I'd love to help!

**Comment by JarredLHumphrey** [comment]
@solatis @ztellman any updates here? Would be happy to help if it would facilitate pushing this forward.

**Comment by ztellman** [comment]
It's been stalled for lack of help, so that would be greatly appreciated.

**Comment by kachayev** [comment]
@ztellman I think it's absolutely safe to close this one already as far as multipart functionality is implemented and merged into master.
