### ISSUE TITLE
'utilization-executor' + 'queue-length' resulting in poor behaviour

### ISSUE THREAD

**Issue by xsc** [ztellman/aleph#164]
The following piece of code starts up an aleph server using a custom `utilization-executor` and `:queue-length`:

```clojure
(require '[aleph.http :as http] '[aleph.flow :as flow])

(defn make-executor
  []
  (flow/utilization-executor
    0.95
    16
    {:queue-length 1000
     :control-period 500}))

(defn start
  []
  (http/start-server
    (fn [_]
      (Thread/sleep 1000)
      {:status 200})
    {:port 8080
     :executor (make-executor)}))
```

Now, starting the server and using e.g. `siege` to bombard it with with more requests than it can immediately handle - i.e. filling up the queue - exhibits IMO less than ideal behaviour.

The first bombardment results in gradual pool size increase, as expected, resulting in ~1s response time after a while:

```
$ siege -v -b -c 20 http://localhost:8080
[...]
HTTP/1.1 200   1.24 secs:       0 bytes ==> GET  /
HTTP/1.1 200   1.11 secs:       0 bytes ==> GET  /
HTTP/1.1 200   1.10 secs:       0 bytes ==> GET  /
HTTP/1.1 200   1.10 secs:       0 bytes ==> GET  /
HTTP/1.1 200   1.11 secs:       0 bytes ==> GET  /
[...]
Response time:                  1.39 secs
[...]
```

Letting the pool cool down, then retrying the experiment shows a different result:

```
$ siege -v -b -c 20 http://localhost:8080
[...]
HTTP/1.1 200  20.01 secs:       0 bytes ==> GET  /
HTTP/1.1 200  20.01 secs:       0 bytes ==> GET  /
HTTP/1.1 200  20.01 secs:       0 bytes ==> GET  /
HTTP/1.1 200  20.01 secs:       0 bytes ==> GET  /
HTTP/1.1 200  20.01 secs:       0 bytes ==> GET  /
[...]
Response time:                 13.23 secs
[...]
```

The server basically became single-threaded during the second run which can't be intentional, although maybe I'm just using the `utilization-executor` in an unintended way...

---

```
$ lein version
Leiningen 2.5.0 on Java 1.7.0_67 Java HotSpot(TM) 64-Bit Server VM
```

```
$ cat project.clj 
(defproject aleph-utilization-demo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0-beta2"]
                 [aleph "0.4.0"]])
```

**Comment by ztellman** [comment]
Try setting `:initial-thread-count` to 16 or something and see how that changes the behavior.  The only real-time thread growth (between the control periods, which are only every 10 seconds by default) happens when the queue is full, which won't happen when you have 20 clients and a buffer size of 1000.  

However, this still doesn't really address the issue of growing the pool once it's downsized itself.  I've only ever used the utilization executor with an unbuffered queue, and on reflection that may be the only way it makes sense to use it.  Can I ask what your intended behavior was?

**Comment by xsc** [comment]
> Try setting :initial-thread-count to 16 or something and see how that changes the behavior.

I adjusted the executor instantiation to be:

```clojure
(defn make-executor
  []
  (flow/utilization-executor
    0.95
    16
    {:queue-length 1000
     :initial-thread-count 16
     :stats-callback (comp #(prn :num-workers %) :num-workers)
     :control-period 500}))
```

This results in shrinking of the pool while no requests are coming in:

```clojure
:num-workers 16
:num-workers 12
:num-workers 9
:num-workers 6
:num-workers 4
:num-workers 3
:num-workers 2
:num-workers 1
:num-workers 1
...
```

When I start `siege` at any point during the pool's shrinking, `:num-workers` stays constant but does never increase. Compare that to creating the executor without `:initial-thread-count`:

```clojure
:num-workers 1
:num-workers 1
:num-workers 2
...
:num-workers 14
:num-workers 15
:num-workers 16
:num-workers 16
:num-workers 16
```

As mentioned in the original issue, once it goes down to 1 again, that's where it stays.

> Can I ask what your intended behavior was?

Using the utilization executor was less of a conscious choice at first but owned to the fact that it's aleph's [default executor](https://github.com/ztellman/aleph/blob/master/src/aleph/http.clj#L76). However, no requests should be dropped, so I added `:queue-length`, experiencing the described behaviour.

I think, the goal was an executor that just grows and shrinks depending on the load it is faced with - `utilization-executor` felt like the right one.

**Comment by ztellman** [comment]
There's always a possibility of requests being dropped, unless you set your queue to `Integer/MAX_VALUE` or something, but then the requests will just be dropped when you run out of memory.

With the utilization executor I was assuming that the pool would grow immediately, in response to demand.  The controller really only exists to shrink the pool periodically.  If you don't grow the pool immediately, your queue will grow and likely overflow in the time between the increased demand and the controller making the pool grow.  In other words, a queue-size of 0 makes you significantly less likely to drop requests.

I think the answer here is to only use a queue-size of 0 with the utilization executor.  I tried to discourage this by not making it an explicit parameter, but in the next release I'll just spit out a warning if someone tries to set it to a non-zero value and ignore it.  If you want to use a non-zero queue length, use a fixed size executor.

**Comment by xsc** [comment]
> There's always a possibility of requests being dropped.

Ah, yes, I meant to express: "No requests should be dropped that could not be processed in a reasonable timeframe", i.e. if mean response time is ~200ms but fulfilling a request in ~1s is still okay, there may be up to 4 queued requests per worker.

> If you want to use a non-zero queue length, use a fixed size executor.

Fixed-size executor it is, then.

Thanks for the quick feedback!
