### ISSUE TITLE
on-closed callback doesn't seem to be functioning correctly

### ISSUE THREAD

**Issue by mischov** [ztellman/aleph#165]
After the web-socket stream provided by `websocket-connection` is closed, a previously attached `on-closed` callback doesn't appear to get called.

example - https://gist.github.com/mischov/b5b649bc6fab009c5711
project.clj - https://gist.github.com/mischov/48c10ab955873f1098ac

**Comment by ztellman** [comment]
Just tried to reproduce this using the existing tests, and failed.  I added `on-closed` and `on-drained` callbacks to the existing websocket tests (https://gist.github.com/ztellman/a8812c558ce8a4cc54f1), and saw both.

Not sure what the discrepancy is here, but it doesn't seem to be an out-and-out missing piece of functionality, at least.

**Comment by ztellman** [comment]
Further report: I can see the "Goodbye" message. However, in cider I need to open the `*nrepl-server aleph-test*` buffer to do so.  Likewise, when I change the callback to `(stream/on-closed ms #(swap! callback-data conj "Goodbye"))`, I can see it in the atom.  

All of this is done at the REPL in cider-emacs.  Can you elaborate on your testing process?

**Comment by mischov** [comment]
.... Cider.... sigh.
