### ISSUE TITLE
Creating/closing lots of connections causes 100% CPU usage

### ISSUE THREAD

**Issue by deliminator** [ztellman/aleph#167]
There seems to be a leak in aleph.netty/bandwidth-tracker. After creating and closing lots of tcp connections, the ScheduledFuture's callback is still being called. If you create and close 100 000s of connections, then that will eventually use up 100% CPU.

I've added a YourKit tracing sceenshot taken while the JVM was using up 100% of all CPU(s), and the only non-netty code is the bandwidth-tracker:
![aleph-netty-bandwidth-tracker-leak]
(https://cloud.githubusercontent.com/assets/326606/8073779/d1e0ff68-0f6c-11e5-8e85-48fdec880046.png)

Here is a way to reproduce this issue:
```
(require '[aleph.tcp :as tcp])
(require '[manifold.stream :as stream])
(require '[manifold.deferred :as deferred])
(let [server (tcp/start-server
			  (fn [s info]
				(stream/close! s))
			  {:host "localhost" :port 15001})]
  (try
	(dotimes [cnt 100000]
	  (Thread/sleep 1)
	  (let [wait (promise)]
		(-> (tcp/client {:host "localhost" :port 15001})
			(deferred/on-realized
			  (fn [s] (stream/close! s) (deliver wait true))
			  (fn [err] (deliver wait true))))
		@wait))
	(finally
	  (.close server))))
```

**Comment by ztellman** [comment]
Thanks for this report, I'll look into it today.

**Comment by ztellman** [comment]
I'm not able to reproduce this.  I was able to see similar behavior by commenting out [this line](https://github.com/ztellman/aleph/blob/master/src/aleph/netty.clj#L464), but otherwise it works as expected.  

I'm running 

```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

on OS X 10.10.3.  Can you give me more details about your setup?

**Comment by leonardoborges** [comment]
Hey @ztellman 
I can confirm this works on Mac too. I tried it on a linux machine and was able to replicate it. @deliminator is also running on linux so this seems to be platform specific.

**Comment by ztellman** [comment]
Okay, just to narrow it down, are you running OpenJDK or OracleJDK, and
what version?

**Comment by deliminator** [comment]
As @leonardoborges said, I'm using linux:

$ uname -a
Linux maker 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux

Running the following Oracle JDK:
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

Using aleph [aleph "0.4.0"] and [org.clojure/clojure "1.7.0-alpha4"].

I didn't notice at first but we were using an older version of netty through a transitive dependency [io.netty/netty-all "4.0.21.Final"], and I tried to run the test again with aleph's declared netty version [io.netty/netty-all "4.1.0.Beta4"] which causes a different problem making the test run very very slowly. The test is still running, and I'll see if upgrading the dependency resolves this issue.

**Comment by deliminator** [comment]
I'm unable to reproduce the timer leak after upgrading the dependency. Sorry for the false alarm.

As mentioned I ran into some new problems. I created a pull request for one (the on-realized macro duplicating the tcp/client invocation) : https://github.com/ztellman/manifold/pull/39

The other is that I'm getting io.netty.channel.ConnectTimeoutExceptions with the new dependency, which I wasn't getting with the older dependency, while running the same code. Probably netty specific and not a huge deal since I was only able to reproduce it with the example code I posted and it doesn't seem to occur when you do other things like sending messages on the channel. [Here is the repository I used for testing for reference](https://bitbucket.org/deliminator/aleph-test).

**Comment by martinraison** [comment]
For what it's worth (it might actually be a different issue), with netty's advanced leak detection enabled, I occasionally see some stack traces involving `bandwidth-tracker`. I don't know much about netty so the issue could be with the way I'm actually using aleph (I have `raw-stream` enabled in the server). I thought I'd just let you know. I also can't find a reliable way to reproduce it. Anyway I'll update to the latest beta to bypass `bandwidth-tracker` altogether.

**Comment by ztellman** [comment]
Hi Martin,

I was able to see <5% CPU overhead due to 100k outstanding connections, and high connection churn lead to a similar problem (each connection has at least one periodic event registered before it's closed).  You should definitely upgrade to the latest version if you're seeing issues.

Zach
