### ISSUE TITLE
HTTP client hangs while trying again after a connection error

### ISSUE THREAD

**Issue by pbwolf** [ztellman/aleph#168]
After attempting to contact a port that nothing is listening to, trying again with the same pool hangs even if a server is listening.

Steps to reproduce in REPL with Aleph 0.4.0:

1. (require '[aleph.http :as http])

2. @(http/get "http://localhost:2287/")
ConnectTimeoutException connection timed out: localhost/127.0.0.1:2287  io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe$1.run (AbstractEpollStreamChannel.java:458)

3. @(http/get "http://localhost:2287/")
(hangs)

**Comment by ztellman** [comment]
I'm not able to reproduce this.  Can you provide some more details as to your environment, and the output of `lein deps :tree`?

**Comment by pbwolf** [comment]
Here are "lein deps"; a short program that encounters the
issue if I build it into an uberjar and run the jar without lein; the exception it catches (in the first iteration); and a description of computers I have tried.

```
$ lein deps :tree
 [aleph "0.4.0"]
   [byte-streams "0.2.0"]
     [clj-tuple "0.2.1"]
     [primitive-math "0.1.4"]
   [io.aleph/dirigiste "0.1.0"]
   [io.netty/netty-all "4.1.0.Beta4"]
   [manifold "0.1.0"]
     [riddley "0.1.9"]
   [org.clojure/tools.logging "0.3.1"]
   [potemkin "0.3.13"]
 [ch.qos.logback/logback-classic "1.1.3"]
   [ch.qos.logback/logback-core "1.1.3"]
   [org.slf4j/slf4j-api "1.7.7"]
 [cider/cider-nrepl "0.8.2"]
   [cljs-tooling "0.1.3" :exclusions [[org.clojure/clojure]]]
   [compliment "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/java.classpath "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.namespace "0.2.5" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.trace "0.7.8" :exclusions [[org.clojure/clojure]]]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.7.0-RC2"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]
```

Here is a short program that encounters the issue if I build it into an
uberjar and run the jar without lein:

```
(ns prb.pool
  (:gen-class)
  (:import (java.util Date))
  (:require [aleph.http :as http]))

(defn -main [url]
  ""
  (dotimes [n 10]
    (try
      (println (Date.) "GET" n)
      (let [df (http/get url)
            rv @df]
        (println  (Date.) "Done:" rv))
      (catch Exception e
        (println  (Date.) "Caught" e)))
    (Thread/sleep 5000)))
```

The exception it catches (in the first iteration) looks like this:

```
 #error {
 :cause connection timed out: localhost/127.0.0.1:2287
 :via
 [{:type io.netty.channel.ConnectTimeoutException
   :message connection timed out: localhost/127.0.0.1:2287
   :at [io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe$1 run AbstractEpollStreamChannel.java 458]}]
 :trace
 [[io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe$1 run AbstractEpollStreamChannel.java 458]
  [io.netty.util.concurrent.PromiseTask$RunnableAdapter call PromiseTask.java 38]
  [io.netty.util.concurrent.ScheduledFutureTask run ScheduledFutureTask.java 120]
  [io.netty.util.concurrent.SingleThreadEventExecutor runAllTasks SingleThreadEventExecutor.java 322]
  [io.netty.channel.epoll.EpollEventLoop run EpollEventLoop.java 254]
  [io.netty.util.concurrent.SingleThreadEventExecutor$4 run SingleThreadEventExecutor.java 703]
  [io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator run DefaultThreadFactory.java 137]
  [java.lang.Thread run Thread.java 745]]}
```

I have tried this on Ubuntu 15.04 (8 "processors" in /proc/cpuinfo)
and Fedora 22 (4 "processors").

**Comment by ztellman** [comment]
I suspect the difference in behavior is due to the use of the epoll client, but I don't have the time to test it today, and will be on an international flight tomorrow.  Can you try adding this to the top of your test, and tell me if the behavior changes?

```clj
(alter-var-root #'aleph.netty/epoll? (fn [_] (constantly false)))
```

**Comment by pbwolf** [comment]
That's it!  Turning off epoll takes some doing, because it's used in a def a little farther down in netty.clj.  By the time my program altered the root binding, it was too late.  Copying aleph into my project and changing netty.clj's definition of "epoll?" made it work well:  It reported java.net.ConnectException "Connection refused" right away instead of waiting to time out, and it successfully connected in a subsequent loop iteration after I started a process listening to the port.

**Comment by ztellman** [comment]
Hmm, I've used an alter-var-root like that to successfully disable epoll
before, but obviously it should be explicitly configurable, and maybe off
by default. I'll update the issue once that's the case.

**Comment by ztellman** [comment]
`:epoll?` is now an explicit parameter, and false by default.  Thanks for the report.
