### ISSUE TITLE
Question: Large responses when Aleph behind nginx?

### ISSUE THREAD

**Issue by zentrope** [ztellman/aleph#169]
I've got an app serving up a large clojurescript file. Works great when I run the app standalone or from an uberjar.

When I put the standalone app behind an nginx proxy, I have trouble downloading the "main.js" file via proxy_pass.

    49902#0: *461 upstream prematurely closed connection while reading upstream, client

Under advanced optimization, the file is still 300K. I'm not interested in a fast download (yet), just a consistent one.

The operative code is here: [github](https://github.com/zentrope/cipher/blob/master/src/clj/cipher/main.clj#L169-L183) It reads resource files from the file system into a response.

I tried using a `deferred` for the whole response (actually reading the files in a thread), or returning a `stream` as the body. Not much better.

What I have _not_ tried is chunking the read from the file(s) and putting them to the stream in fixed sized chunks.

Is that that preferred strategy for large (3MB or 300K) files served out via Aleph?

Is there maybe something problematic with nginx 1.8.0?

Finally, there are options to adjust ServerBootstrap (and a few other objects), though I found the javadoc for those, uh, not immediately obvious. Is that where to look?

**Comment by ztellman** [comment]
This shouldn't be a problem, size-wise.  "Prematurely closed" may imply that nginx received fewer bytes than the "Content-Length" indicates, which is a bit odd.  [This link](http://community.apigee.com/questions/1274/nginx-reverse-proxy-to-apigee-upstream-prematurely.html) suggests that it may be something more fundamental relating to even opening the connection. If you get it via `curl`, is it successful?

**Comment by zentrope** [comment]
If the payload is large enough, I can reproduce it with curl. The un-optimized Clojurescript file (3MB) is clipped each time.

**Comment by zentrope** [comment]
Curl:

    curl -v http://127.0.0.1/main.js

Produces:

```
< HTTP/1.1 200 OK
* Server nginx/1.8.0 is not blacklisted
< Server: nginx/1.8.0
< Date: Mon, 06 Jul 2015 08:21:18 GMT
< Content-Type: application/javascript
< Content-Length: 3442244
< Connection: keep-alive
```

But results in the following error:

```
* transfer closed with 2804779 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 2804779 bytes remaining to read
```

The file itself is `3442244` on the file system.

Again, works just fine if nginx is taken out of the equation.

**Comment by zentrope** [comment]
Nginx config:

https://gist.github.com/zentrope/46223e81159bcd50fdce

**Comment by ztellman** [comment]
Hmm.  I honestly don't know what might be going on here.  One thing I'd suggest is just passing in a `java.io.File` back as the body, as that's more efficient and might (?) change the behavior.  Alternately, you can just use `byte-streams/to-*` to create a stream of chunks, and see how that behaves.

**Comment by zentrope** [comment]
Okay. I'll give it a shot tomorrow. Thanks!

**Comment by zentrope** [comment]
Okay, some interesting new data points:

Using:

```clojure
[aleph "0.4.1-alpha1"]
```

If I chunk the response `(to-byte-buffers {:chunck-size 2048})` , things seem a little better, but there are still premature closes unless I explicitly delay the closing of the stream.

Here's the code:

```clojure
(good-response [rsrc path]
 (let [stream (stream/stream)]
   (async/thread
     (doseq [b (bs/to-byte-buffers rsrc {:chunk-size 2048})]
       (stream/put! stream b))
     (Thread/sleep 100)
     (stream/close! stream))
   {:status 200
    :body stream
    :headers {"content-type" (mime-for path)}}))
```

Notice the `(Thread/sleep 100)`. Doing that results in there _never_ being a premature close in a browser, even when I right `cmd-R` without letting up.

However, `curl` with -v, printing out the data on the console each time, will sometimes result in the premature close.

     curl -v http://doom.local/main.js

but doing this:

     curl -v http://doom.local/main.js > /dev/null

never results in the problem (at least as fast as I can up-arrow-return it).

**Comment by ztellman** [comment]
Hmm, that's a very odd set of workarounds. To clarify, those curls are to
Nginx, or straight to the server?

**Comment by zentrope** [comment]
Nginx. Everything works great with just Aleph almost no matter what I do.

**Comment by ztellman** [comment]
Okay, if you block on the put! calls in your loop, I predict there won't be
any need for the sleep. Can you confirm? I won't be able to reproduce your
setup until I'm back home later this week.

**Comment by zentrope** [comment]
Confirmed. Works great!

**Comment by zentrope** [comment]
Using this nginx config: https://github.com/zentrope/cipher/blob/master/etc/nginx.conf, for what it's worth.

**Comment by ztellman** [comment]
Okay, I think I may know what the issue is, though I still haven't tested anything.  Can you pull the latest from the repo, `lein install` it, and tell me whether it all works without any special chunking, etc.?

**Comment by zentrope** [comment]
Worked.

I removed the `stream` stuff, and just return a java.o.File in the body, or an InputStream (when running from an uberjar) and it all works great.

**Comment by ztellman** [comment]
I've cut `0.4.1-alpha2`, which contains this fix.  Thanks for the report.

**Comment by zentrope** [comment]
Thanks!
