### ISSUE TITLE
NPE trying to view udp socket streams.

### ISSUE THREAD

**Issue by rhg** [ztellman/aleph#170]
When attempting to view a stream, say, in a repl, a NPE is thrown. At first I thought the operation failed, but turns out the correct value is returned, and the .description method throws for some reason.

```
NullPointerException 
        aleph.netty.ChannelSink (netty.clj:274)
        manifold.stream.SplicedStream (stream.clj:371)
        manifold.stream.core/eval16014/fn--16015 (core.clj:73)
        clojure.lang.MultiFn.invoke (MultiFn.java:233)
        clojure.tools.nrepl.middleware.pr-values/pr-values/fn/reify--862 (pr_values.clj:26)
        clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn--881/fn--892 (interruptible_eval.clj:77)
        clojure.main/repl/read-eval-print--7099 (main.clj:241)
        clojure.main/repl/fn--7108 (main.clj:258)
        clojure.main/repl (main.clj:258)
        clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn--881 (interruptible_eval.clj:53)
        clojure.core/apply (core.clj:630)
        clojure.core/with-bindings* (core.clj:1868)
```

**Comment by ztellman** [comment]
Is this 0.4.0 or 0.4.1-alpha1?

**Comment by rhg** [comment]
0.4.0. alpha1 doesn't even form the socket, and instead throws in aleph.udp/socket/reify/channelActive.

**Comment by ztellman** [comment]
Did you mean `0.4.1-alpha1`, or were you actually testing an alpha release of `0.4.0`?

**Comment by rhg** [comment]
Sorry for being vague. This was 0.4.1-alpha1.

**Comment by rhg** [comment]
I just did a git clone and tested several revisions. And strangely 0.4.0-alpha1, 0.4.1-alpha1, and HEAD all worked. I think I'm going slightly mad, but this issue is resolved.

**Comment by rhg** [comment]
FWIW, 0.4.0 does throw using the same test I just did, This is on 7f15c414bbb178290636ea467d25bcc127a31534
