### ISSUE TITLE
Aleph client returning garbled bodies from chunked responses

### ISSUE THREAD

**Issue by tcushman** [ztellman/aleph#171]
When using the Aleph client functions, I'm seeing garbled bodies being returned from requests with chunked responses.  This is occurring for me with Aleph 0.4.0.

To add to the fun, I don't always see this behavior.  The problem seems to be in some way related to how or when Aleph namespaces are loaded.  When loading my full application in the Counterclockwise / Eclipse REPL, I consistently see the behavior.  However, when just loading smaller namespaces that include `aleph.http`, the behavior is less consistent.  Also I haven't noticed the problem when running the application through Leiningen or when loaded in a REPL from Cursive / IntelliJ, though I don't have any firm certainty that it's not happening in those scenarios.

Examples (slightly trimmed down):
```
=> @(aleph.http/get "http://www.google.com" {:as :string})

{:request-time 95,
 :headers {"server" "gws", "content-type" "text/html; charset=ISO-8859-1",
           "transfer-encoding" "chunked",
           "alternate-protocol" "80:quic,p=0",
           "accept-ranges" "none"}
 :status 200,
 :keep-alive? true,
 :connection-time 0,
 :body "<!doctypmore. GoI=functi++},funcd2d2d;baom:-2px;ext-decodecoratiound-pos0 !impord{marginpiaa{dis-moz-boxorder-co#f5f5f5,h)[a]=b}ndom();Lges/silhcookie.mrseInt(d){for(vais);gbar\"><tablew Active

**Comment by ztellman** [comment]
Hmm, I'm trying to reproduce this by just making the request in `aleph.http`, and can't.  Just to help me zero in on where this error is being introduced, can you do the following:

1. Target `[aleph "0.4.1-alpha2"]`
2. See if this has different results:

```clj
(-> @(aleph.http/get "http://www.google.com") :body manifold.stream/stream->seq vec byte-streams/to-string)
```

Thanks!

**Comment by ztellman** [comment]
Sorry, that code snippet is only valid if you're using `raw-stream?`, which you didn't mention, so I think you can safely ignore it.  Making sure it is still happening in the latest version would be helpful, though.

**Comment by tcushman** [comment]
I am able to reproduce it with `[aleph "0.4.1-alpha2"]`.  I'm going to try to work up a project.clj file and namespace that can trigger this.

**Comment by tcushman** [comment]
Ok, I've figured out what is inducing this strangeness.  Using `byte-streams/def-conversion`, I defined conversions for `Long -> bytes` and `bytes -> Long`.

These conversions don't seem to be the sole cause though, it looks like core.async must also be present.  When I include core.async (version 0.1.346.0-17112a-alpha) the behavior is reliably reproducible, and when I remove core.async, then everything seems to behave normally.

So... is it reasonable to expect that defining byte-stream conversions for `Long -> bytes` and `bytes -> Long` should be free of side effects?  Or is this a touchy area when Aleph is also needed?

Reproduction code:  https://gist.github.com/tcushman/e5e82ffe63a09383d912

Dependencies:
```clojure
[org.clojure/clojure "1.7.0"]
[org.clojure/core.async "0.1.346.0-17112a-alpha"]
[aleph "0.4.0"]
```

**Comment by ztellman** [comment]
Haha, okay, I wasn't expecting custom conversions.  A few thoughts:  Your conversions are definitely not 0 cost, there's real copying being done there (as opposed to just wrapping a byte-array in an ByteArrayInputStream).  Also, they don't appear to be fully type-hinted, and would probably be faster if you just did them like this: https://github.com/ztellman/byte-transforms/blob/master/src/byte_transforms.clj#L101-L107.

I still cannot reproduce this, and the code you gave has `(def ^:private LONG-BYTES (Long/BYTES))`, which doesn't seem to be valid in my JVM.  Maybe this is just a typo, or maybe it points to some difference in our environment?

When you're able to reproduce this issue, can you give me the output of `(bs/conversion-path java.io.InputStream String)`?

**Comment by tcushman** [comment]
Those two constants, LONG-BYTES and BYTE-SIZE are both 8.  Long/BYTES is new in Java8.  I'm using Oracle's JDK 1.8.0_51 & 1.8.0_31.  Sometimes everything loads up and runs cleanly, though 8.0_51 seems to pass a little more often than 8.0_31.  It was a bit crazy trying to narrow down the failure condition for something that didn't always fail.

I'll give the ByteBuffer conversion a try.

Below is the conversion path I get for InputStream -> String.  This was taken from a running system that was exhibiting the strangeness.
```clojure
( [ {:on byte_streams.protocols.ByteSource,
     :on-interface byte_streams.protocols.ByteSource,
     :sigs {:take-bytes! {:name take-bytes!, :arglists ([_ n options]),
                          :doc "Takes `n` bytes from the byte source."}},
     :var #'byte-streams.protocols/ByteSource,
     :method-map {:take-bytes! :take-bytes!},
     :method-builders {#'byte-streams.protocols/take-bytes! #object[byte_streams.protocols$eval4720$fn__4721 0x40174927 "byte_streams.protocols$eval4720$fn__4721@40174927"]}}
    java.lang.CharSequence]
  [ java.lang.CharSequence java.lang.String ])
```

**Comment by tcushman** [comment]
Ok, increasing the cost from 0 to 10 seems to inhibit the problem, even though the the conversion paths look identical.  Here is the conversion path returned when the cost of Long -> bytes and bytes -> Long is 10 instead of 0.

```clojure
( [ {:on byte_streams.protocols.ByteSource,
     :on-interface byte_streams.protocols.ByteSource,
     :sigs {:take-bytes! {:name take-bytes!, :arglists ([_ n options]),
                          :doc "Takes `n` bytes from the byte source."}},
     :var #'byte-streams.protocols/ByteSource,
     :method-map {:take-bytes! :take-bytes!},
     :method-builders {#'byte-streams.protocols/take-bytes! #object[byte_streams.protocols$eval4720$fn__4721 0x4126936a "byte_streams.protocols$eval4720$fn__4721@4126936a"]}}
    java.lang.CharSequence ]
  [ java.lang.CharSequence java.lang.String ] )
```
I suspect the protocol referenced by `:method-builders` is hiding some of the details.

**Comment by ztellman** [comment]
The culprit is https://github.com/ztellman/byte-streams/blob/master/src/byte_streams.clj#L514, where there's a hidden conversion to byte-arrays.  It should be enough to change the cost to 1, I'd think.  Can you confirm?

**Comment by tcushman** [comment]
Yes, a cost of 1 seems to be enough.  I suppose that when searching for a cost-based path, any number of a -> b, b -> a conversions could be added into the path if both conversions claim to have no cost.

Thanks for your help on this.  I've got things in working order on my end.

**Comment by ztellman** [comment]
The searches are breadth-first, so you can't infinitely recurse that way, but zero-cost conversions tend to have a graph-warping effect regardless.  Glad it wasn't just a bug on my end that randomly corrupted data.
