### ISSUE TITLE
unexpected http body

### ISSUE THREAD

**Issue by hiredman** [ztellman/aleph#172]
This is my first foray in to aleph country. I expected [this code](https://gist.github.com/hiredman/1036fbee8067d33aa0b4) to run forever, but instead it runs for a while and then exits because the http body returned is not the expected value.

I am using aleph 0.4.0 and have seen this with both clojure 1.7 and 1.6

**Comment by ztellman** [comment]
If the body is not the expected value, what is it?

**Comment by hiredman** [comment]
the empty string

**Comment by hiredman** [comment]
or I should say, whatever the body is, if you slurp it, you get the empty string

**Comment by ztellman** [comment]
How long did it take for this issue to occur on your system?  I've been running it for a few minutes both on 0.4.0 and the latest master, and am not seeing any such issue.  Other details like your JVM version, OS, etc. may help.

**Comment by hiredman** [comment]
wall clock time to exit is generally around 80-100 seconds for me

I am running my little example on OSX, with my own build of java 1.9, but I have observed the same behavior on linux with oracle's 1.7.0_80

**Comment by hiredman** [comment]
the md5 for ~/.m2/repository/aleph/aleph/0.4.0/aleph-0.4.0.jar on both my linux machine and osx is ac21d596f53515841f150bab516a0830

**Comment by ztellman** [comment]
Hmmm.  In the `0.4.1` release I've disabled epoll usage by default in Linux, can you confirm this is still happening with the `master` branch?  As I said, I'm unable to reproduce it in either version, but the epoll stuff has caused the most weird behavior in the past.

**Comment by hiredman** [comment]
this last run got an exception printed out before exiting
```
Aug 13, 2015 4:35:12 PM clojure.tools.logging$eval710$fn__714 invoke
WARNING: error in HTTP server
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: DefaultHttpContent
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:158)
	at io.netty.channel.DefaultChannelHandlerInvoker$WriteTask.run(DefaultChannelHandlerInvoker.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:322)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: unexpected message type: DefaultHttpContent
	at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:92)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 7 more
```

**Comment by hiredman** [comment]
running again on OSX with a build of master, it is looking promising, no exit after two minutes, so whatever it is, it seems like it is fixed on master?

**Comment by ztellman** [comment]
Okay, I wish I had some clarity on what caused the behavior you're seeing, but that's probably not going to come easy.

**Comment by df-unhuman** [comment]
https://stackoverflow.com/questions/15097966/unexpected-message-type-defaulthttprequest-on-a-httpclientcodec-pipeline 

I seem to be getting this issue. Searching gave me the above link. Unfortunately I am not sure how to implement their suggestion.

Is it something in my setup? 

Thanks.

**Comment by ztellman** [comment]
The behavior discussed in the SO issue is handled for you by Aleph.  What version of Aleph are you using?

**Comment by df-unhuman** [comment]
Apologies. Was still on 0.4.0, latest has no issues. 

Thank you.

**Comment by ljosa** [comment]
I got the `unexpected message type: DefaultHttpContent` exception in aleph 0.4.0 when a client hung up on a server-sent–events connection. However, the exception is gone in aleph 0.4.1-beta2.

(Just leaving this here as a breadcrumb.)
