### ISSUE TITLE
Depend on a stable (non-beta) version of Netty 

### ISSUE THREAD

**Issue by aamedina** [ztellman/aleph#179]
We've run into API incompatibilities with other co-dependent libraries with Netty because of this dependency. 

Thank you!

**Comment by ztellman** [comment]
As far as I'm concerned, at least for the subset of features that Aleph uses Netty 4.1.0 is stable.  HTTP servers running the code have handled roughly half a trillion requests so far.  I'm happy to walk you through what you'd need to change if you want to fork Aleph, but I'd prefer to keep it as-is in the canonical release.

**Comment by aamedina** [comment]
I'm not saying that the code isn't reliable for use in production; sorry if I implied that. I meant that the Netty API is in flux in the beta releases, classes change names, methods get removed/added etc. Sometimes these small API changes introduce tiny bits of complexity into a downstream app that needs to rely on more than one library which is co-dependent on Netty. Therefore clipping Aleph to a released version of Netty makes it easier to work with the ecosystem at large without dropping down to external code modification or rewriting useful bits from other libraries. Another practical concern is that the beta releases come more often (by design), and taking advantage of these new features and/or keeping up with small changes in the API would be desirable. If Aleph were to keep pace with the Netty beta releases this wouldn't be a problem, but if you try to use the latest 4.1.0 beta with Aleph you will see breaking changes in the classes exposed for example.
