### ISSUE TITLE
Pass custom ssl-context to client

### ISSUE THREAD

**Issue by martinraison** [ztellman/aleph#183]
I don't think there's any non-hacky way to override which ssl-context is used by the http and tcp clients:

https://github.com/ztellman/aleph/blob/7309ab10a18f96be8a68cd1536e837d117ac56da/src/aleph/http/client.clj#L294
https://github.com/ztellman/aleph/blob/b62525a13ccdcccba8f0e0ebbe8b39a2314c8d1d/src/aleph/tcp.clj#L154

Being able to pass an `ssl-context` option (just like for the http server) would be nice. In the case of the http client, it might be an option passed when building the connection pool.

This feature is supported by clj-http (through the `trust-store`, `trust-store-type`, `trust-store-pass` options).

**Comment by ztellman** [comment]
Yeah, that's definitely a weird asymmetry in the API, I can add an `:ssl-context` option.

**Comment by martinraison** [comment]
Thanks!
