### ISSUE TITLE
Migrate websockets from 0.3.2 to 0.4.0

### ISSUE THREAD

**Issue by ognivo** [ztellman/aleph#185]
I'm trying to upgrade from 0.3.2 to 0.4.0, but it seems that it is not a drop-in update.
Can you walk with me through upgrade steps? Maybe it will help other users as well.

So far I've done:
### 1. Deps update
Was:
```clojure
    [[org.clojure/clojure        "1.7.0" ]
     [ring/ring                  "1.3.2" ]
     [ring/ring-json             "0.3.1" ]
     [compojure                  "1.1.8" ]
     [aleph                      "0.3.2" ]
     [lamina                     "0.5.4" ]]
```
Now:
```clojure
    [[org.clojure/clojure        "1.7.0" ]
     [ring/ring                  "1.4.0" ]
     [ring/ring-json             "0.4.0" ]
     [compojure                  "1.4.0" ]
     [aleph                      "0.4.0" ]
     [lamina                     "0.5.6" ]] ; still using lamina for some internal tasks, want to upgrade to manifold later
```
### 2. Threw off `aleph.http/wrap-ring-handler` call in init function
Was:
```clojure
(defn run-web []
  (def kill-aleph-fn
  (aleph/start-http-server
    (aleph/wrap-ring-handler app-routes/router)
    {:host cfg/APP_HOST :port cfg/APP_PORT
     :netty  {:pipeline-transform #(doto % (.remove "deflater"))}
     :websocket true})))
```
Now:
```clojure
(defn run-web []
  (def kill-aleph-fn
  (aleph/start-server
    app-routes/router
    {:host cfg/APP_HOST :port cfg/APP_PORT
     :netty {:pipeline-transform #(doto % (.remove "deflater"))}
     :websocket true})))
```
### 3. Threw off `aleph.http/wrap-aleph-handler` call
Was:
```clojure
(defroutes router
  (GET "/ws" [] (aleph/wrap-aleph-handler socketd/handler)))
```
Now:
```clojure
(defroutes router
  (GET "/ws" [] socketd/handler))
```
### 4. Updated the old websocket handler
Was:
```clojure
(defn handler [ch {:keys [user-id] :as req}]
  (register-user-channel user-id ch)
  (let [receive (fn [ch] (lamina/receive-all ch #(process-ws-data user-id %)))
        chat (lamina/channel)]
  (lamina/receive chat)
  lamina/(siphon ch chat)))
```
Now:
```clojure
(defn ye-olde-handler [ch {:keys [user-id] :as req}]
  (register-user-channel user-id ch)
  (let [receive (fn [ch] (lamina/receive-all ch #(process-ws-data user-id %)))
        chat (lamina/channel)]
  (lamina/receive chat)
  (lamina/siphon ch chat)))

(defn handler [req]
  (let [ch (aleph/websocket-connection req)]
  (ye-olde-handler ch req)))
```
### 5. Stuck with exception
`java.lang.ClassCastException: manifold.deferred.Deferred cannot be cast to lamina.core.channel.IChannel`

**The old code was written for lamina channels, is there some of official workaround for this? If I could somehow "cast" Deferred to Channel, this should be enough the rest of the app to work.**
**Is there anything else that I missed?**

**Comment by ztellman** [comment]
I'm sorry, I somehow missed this when you first opened the issue.  The issue here is that `aleph/websocket-connection ` doesn't return a channel, it returns a deferred that yields a channel if the websocket handshake succeeds.  In the simplest case, just dereference the result of `websocket-connection` and you're good to go.

I'm going to close the issue, please let me know if this doesn't fix your issue.

**Comment by ognivo** [comment]
Applied your hint. Now I have new exception: `java.lang.ClassCastException: manifold.stream.SplicedStream cannot be cast to lamina.core.channel.IChannel`

My app uses lamina to queue stuff. So, is there a way to somehow "cast" manifold's SplicedStream  to lamina channel?

**Comment by ztellman** [comment]
You'll need to coerce the Manifold stream to a Lamina channel, like so:

```clj
(defn wrap-manifold-socket [s]
  (let [source (lc/channel)
         sink (lc/channel)]
    (ms/connect source s)
    (ms/connection s sink)
    (lc/splice sink source))
```

Let me know if that doesn't work.

**Comment by ognivo** [comment]
Yeah! Seems like its working. Thank you so much!

There's a typo: `ms/connection` should be `ms/connect`.

**Comment by ztellman** [comment]
Whoops, sorry for the typo.
