### ISSUE TITLE
StringIndexOutOfBoundsException from aleph.http.client-middleware/generate-query-string

### ISSUE THREAD

**Issue by pbwolf** [ztellman/aleph#186]
user> (require '[aleph.http.client-middleware :as ahcm])
nil
user> (ahcm/generate-query-string {:a "3"})
StringIndexOutOfBoundsException String index out of range: -1  java.lang.AbstractStringBuilder.substring (AbstractStringBuilder.java:904)

Expected result

user> (ahcm/generate-query-string {:a "3"})
"a=3"

Looking at the code, I think there are two problems. (1) The "(if (sequential? v)" test is not needed: it has no "else", so it causes non-collection values to be skipped, and anyway the "true" branch has its own if-sequential test and seems to be able to deal with strings. (2) The concluding substring invocation uses the arity-1 version, which starts at an offset, but the generate-query-string function's intent is to select all but the last character, so it should use the arity-2 version with 0 as the first argument.

This is with respect to Aleph 0.4.1-beta1.

**Comment by ztellman** [comment]
Since this was a major (stupid) bug, I've marked a new release for this fix.  Thanks again for the report.
