### ISSUE TITLE
Add support for cookiestore

### ISSUE THREAD

**Issue by stijnopheide** [ztellman/aleph#188]
I don't know whether this should be a responsibility of the aleph http client, but clj-http supports a cookie-store.

The use case is following a redirect chain in which cookies are being set along the way. Currently you'd have to turn of `follow-redirects?`, store the cookies after each response and then get the next redirect in the chain.

**Comment by kachayev** [comment]
Closing this due to https://github.com/ztellman/aleph/commit/86fdae60b08a1d85a54773e3bfbfdfbe2392366c
