### ISSUE TITLE
Date Response Header Formatted Incorrectly

### ISSUE THREAD

**Issue by solicode** [ztellman/aleph#190]
On my machine, Aleph is returning Date headers like `?, 13 11 2015 11:43:28 GMT` when I'm actually expecting `Fri, 13 Nov 2015 11:43:28 GMT`.

This is happening because I'm on a Japanese machine, and a Japanese Locale is being used by default. The problem seems to be:

```clojure
(SimpleDateFormat. "EEE, dd MMM yyyy HH:mm:ss z")
```

I believe this should something like this instead:

```clojure
(SimpleDateFormat. "EEE, dd MMM yyyy HH:mm:ss z" Locale/ENGLISH)
```

I looked up RFC 1123, and I couldn't see any mention on what to do about different languages. But RFC 822 shows only English day and month names, so I'm guessing that means these should always be English.

Besides, I believe headers are supposed to be ASCII only, so it would be impossible to make this work with all languages, right? And that's probably why I'm seeing a question mark for `金` ("Friday" in Japanese).

**Comment by ztellman** [comment]
Interesting, I just copied some of the existing examples for Netty, I guess theirs is incorrect as well.  Thanks for the report!
