### ISSUE TITLE
Intermittent Incomplete Chunked Encoding Errors on various clients 

### ISSUE THREAD

**Issue by aamedina** [ztellman/aleph#191]
Can reproduce with clj-http pretty consistently. It seems to fail probabilistically.

**Comment by ztellman** [comment]
Which version?

**Comment by aamedina** [comment]
0.4.1-beta2, I am investigating what commits introduced this behavior now.

**Comment by aamedina** [comment]
It looks like this should be reproducible in 0.4.1-beta1 as well, because beta2 does not introduce any new relevant behavior. Specifically, the code in `send-streaming-body` in src/aleph/http/core.clj, which closes the body before enqueuing the last message might introduce a race condition.

**Comment by ztellman** [comment]
Your fix seems fine, but what data structure were you using for your streaming body?

**Comment by aamedina** [comment]
I've been seeing it with almost any type of response. But generally a (deferred) ring response.

**Comment by aamedina** [comment]
(So a persistent hash map, before the middleware transform it into a JSON string)

**Comment by ztellman** [comment]
A chunked response should only be used for a streaming body.  A string shouldn't be streamed, unless it's been turned into an InputStream.

**Comment by ztellman** [comment]
Okay, actually, having looked at this a little closer, this doesn't make sense to me.  The call to `.execute` you're reverting is intended to get rid of a race condition.  If you want to move the call to .close into that function, that's fine, but I'm still a bit confused as to what you're returning, since that function should only be executed when it's an InputStream or something similar.

**Comment by aamedina** [comment]
We're using Compojure to manage our routes. The Renderable protocol has been extended to accept Deferred responses and return them to Aleph for asynchronous processing. An InputStream is being created for the response body internally by Compojure.

**Comment by aamedina** [comment]
Additionally, with the change we encounter no stochastic chunking exceptions. By enqueuing that write-and-flush, it races to the final chunk. It's a very insidious problem - you can see it in 1 out of 100 requests if you're unlucky, but it will happen.

**Comment by aamedina** [comment]
Not that it should ultimately matter what middleware we're using in our application for formatting the response, but I found the LOC where the transformation takes place: https://github.com/ngrunwald/ring-middleware-format/blob/master/src/ring/middleware/format_response.clj#L200

**Comment by ztellman** [comment]
Can you provide a minimal reproducing case for this?  It's certainly possible that my fix caused other issues, but it definitely fixed another class of bug that resembles what you're describing, so I'd like to have something that I can play around with a bit.

**Comment by aamedina** [comment]
That makes sense, I will put together a minimally reproducible test case ASAP for you. Thanks for your help! We use Aleph in production at Vital Labs btw - I think you've met the CEO, Ian Eslick. So big fans here. :)

**Comment by ztellman** [comment]
Thank you for the report, it's definitely something I want to fix before pushing 0.4.1 out the door.

**Comment by aamedina** [comment]
I made a repository you can clone and load locally: https://github.com/VitalLabs/aleph-191.git

I included most of the relevant formatting middleware we use for your perusal, if that is helpful in diagnosing the issue.

The issue is insidious - you shoot off many one off GET requests without issue, it only stochastically fails when you lose the race somewhere. I commented out a piece of code you can run which in my experience will trigger the exception when you eval it.

**Comment by ztellman** [comment]
I'll look into this tonight, thank you.
