### ISSUE TITLE
unicode, freebsd, openjdk8 and websockets: unicode chars being whacked?

### ISSUE THREAD

**Issue by zentrope** [ztellman/aleph#196]
I'm using aleph's websocket-connection and transit and I have a question about the raw-stream? flag for the web-socket-connect. 

But first, a weird thing:

When I deploy the server on `FreeBSD` (using `OpenJDK8`), unicode characters such as ø typed into a web form, encoded via transit, sent via web socket, come out as "?" on the Aleph side even before I send the string to transit for decoding.

In other words, (stream/take! ws-stream), already produces the ? rather than the ø.

The byte sequence (-61 -72) becomes 63 (a "?") and eveyrthing else remains the same.

Everything works fine when the server runs on OSX (or maybe it's Oracle's JDK8), remote or localhost.

Using EDN instead of transit works fine. Huh? Typing international characters into the web form, doing a (pr-str value) and sending that via the websocket, then taking it from the stream and applying clojure.edn/read-string works just fine.

How can that be? Either one of these things is just a raw string when on the web-socket wire!

SO, what I tried to do is add :raw-stream? true to the websocket-connection-options in hopes that whatever manifold or netty or the JVM is doing is minimized, but I still get a string-type back out when I do a stream/take. How can I get at the raw bytes before the web-socket payload is converted to a string?

My set up:

```clojure
        options {:raw-stream? true
                 :headers (-> (select-keys headers ["sec-websocket-protocol"
                                                    "sec-websocket-version"])
                              (assoc "content-type" "application/octet-stream"))}
        stream @(http/websocket-connection req options)
```

Used as:

```clojure
(decode @(stream/take! stream))
```

And decode:

```clojure
(defn- decode
  [payload]
  (println "DECODE:" (type payload) payload)
  (when payload
    (with-open [in (ByteArrayInputStream. (bs/to-byte-array payload))]
      (let [reader (transit/reader in :json)]
        (transit/read reader)))))
```

The `(type payload)` is still a string and payload contains the "?" character before I ever send it to the transit stuff. I use the to-byte-array function because I expected payload to be some sort of stream (otherwise .getBytes works).

Any tips for getting to the underlying byte buffers?

**Comment by ztellman** [comment]
If the WebSocket frames are string frames, they'll be decoded for you.  You can send binary frames if you want to bypass that.

**Comment by zentrope** [comment]
Alas, I just don't have any time to figure this out and it's pointless that this remains an open issue here. Reverted to using Clojure EDN rather than transit and will investigate again if "speed" is of the essence.
