### ISSUE TITLE
[question] NullPointerException on nil HTTP header

### ISSUE THREAD

**Issue by gsnewmark** [ztellman/aleph#197]
In case HTTP response headers map contains `nil` values, Netty would throw the NPE when trying to add such header:

```
user> (require '[aleph.http.core :as hc])
nil
user> (import io.netty.handler.codec.http.DefaultHttpHeaders)
io.netty.handler.codec.http.DefaultHttpHeaders
user> (hc/map->headers! (DefaultHttpHeaders.) {"Location" nil})
NullPointerException value  io.netty.util.internal.ObjectUtil.checkNotNull (ObjectUtil.java:31)
```

The same code worked on Aleph 0.4.0 (based on the Netty 4.1.0.Beta4), and stopped working after update to Netty 4.1.0.Beta6.

So, is this NPE an intended behavior?

**Comment by ztellman** [comment]
This isn't intentional, but what is the expected behavior when the value is nil?  An empty string as the value?  Skipping the header entry altogether?

**Comment by gsnewmark** [comment]
Previous version (0.4.0) skipped the header, but I'm not sure it's the best possible behavior. It's not uncommon to think of `nil` values as absent keys (and our app actually intentionally filled headers with `nil`'s in some cases instead of `dissoc`'ing the keys), but in general case it could probably lead to some nasty 'hidden' errors (when `nil` is added by the application code erroneously instead of the correct value).

So, for backwards compatibility it makes sense to skip the headers, but NPE may be OK too (I think `IllegalArgumentException` with message about which header has `nil` value would be better, but it's a matter of preference).

**Comment by ztellman** [comment]
Yeah, I'm leaning towards IllegalArgumentException myself.  Thanks for the report.
