### ISSUE TITLE
Ring compatibility w/out client middleware

### ISSUE THREAD

**Issue by moea** [ztellman/aleph#198]
In the absence of a `:url` key, it looks like [client/req->domain](https://github.com/ztellman/aleph/blob/master/src/aleph/http/client.clj#L66) assumes `:host` and `:port` keys in the request.  To support rock-bottom Ring requests, It seems like it might be reasonable to look at `:server-name` and `:server-port`?  If that makes sense, I'm more than happy to tackle this, though I don't have information on the necessity of continuing to support `:host`/`:port`.

**Comment by ztellman** [comment]
This code is taken pretty much verbatim from `clj-http`, whichis what I'm trying to maintain compatibility with on the client side.  I'm fine with supporting Ring aliases, though.
