### ISSUE TITLE
byte array truncation in tcp transportation

### ISSUE THREAD

**Issue by shisoft** [ztellman/aleph#201]
I am using nippy to serialize clojure data and send to tcp servers. As the example provided with some modifaction. I found that when the data is less than 1024 bytes, everything is fine. When above, I can only get 1024 bytes at server. 
I think this problem is 2-way, when the request data is small and the responses are big, client cannot decode data either.

Here is the wrapper I use.
```
(defn wrap-duplex-stream
  [s]
  (let [out (s/stream)]
    (s/connect out s)
    (s/splice out s)))

(defn client
  [host port]
  (d/chain (tcp/client {:host host, :port port})
           #(wrap-duplex-stream %)))

(defn start-server
  [handler port]
  (tcp/start-server
    (fn [s info]
      (handler (wrap-duplex-stream s) info))
    {:port port}))
```

**Comment by ztellman** [comment]
You can't assume that each packet is a single Nippy frame.  TCP is a streaming protocol, which means that things can be split up arbitrarily across packets (many Nippy frames in a single packet, a single Nippy frame split across N packets, etc).  The typical way to handle this is to prefix each frame with a 32-bit integer describing how many bytes follow, and then reading out that many bytes before passing it to your decoder.

You may find my Gloss project helpful here, examples of how it's used can be found here: http://aleph.io/aleph/literate.html#aleph.examples.tcp.

**Comment by shisoft** [comment]
Thanks for your reply. I have reviewed gloss, but I don't really know how to use it for pure byte array instead of strings. Please give me some hints

**Comment by shisoft** [comment]
I did some search on your `string` function, still cannot figure out how to get byte array from SingleBufferSequence and MultiBufferSequence

**Comment by ztellman** [comment]
Call `byte-streams/to-byte-array`.

**Comment by shisoft** [comment]
That works, I start to getting complete binary data
But the stream is still breaking, server handler did not get any data.

Anther strange phenomena  is that the codec encode and decode `nil` when the actual data transferred.
```
(defn print-byte-arr [byte-arr desc]
  (spy [desc (count byte-arr) (vec byte-arr)])
  (spy (nippy/thaw byte-arr))
  byte-arr)

(defn buffer->byte-array [buf-seq]
  (byte-streams/to-byte-array buf-seq))

(defn bytes-codec []
  (reify
    Reader
    (read-bytes [this buf-seq]
      (let [buf-seq (dup-bytes buf-seq)
            byte-arr (buffer->byte-array buf-seq)]
        [true (nippy/thaw byte-arr) buf-seq]))
    Writer
    (sizeof [x]
      nil)
    (write-bytes [x y obj]
      [(ByteBuffer/wrap (nippy/freeze obj))])))

(def protocol
  (gloss/compile-frame
    (gloss/finite-frame
      :uint32
      (bytes-codec))))


(defn wrap-duplex-stream
  [protocol s]
  (let [out (s/stream)]
    (s/connect
      (s/map #(io/encode protocol %) out)
      s)
    (s/splice
      out
      (io/decode-stream s protocol))))

(defn client
  [host port]
  (d/chain (tcp/client {:host host, :port port})
           #(wrap-duplex-stream %)))

(defn start-server
  [handler port]
  (tcp/start-server
    (fn [s info]
      (handler (wrap-duplex-stream s) info))
    {:port port}))
```

**Comment by shisoft** [comment]
I finally accomplished by `gloss/repeated`, but I got vec instead of byte array at post-decoder function, which need to convert by `byte-array`, it should be a overhead.
