### ISSUE TITLE
TLS client certificates

### ISSUE THREAD

**Issue by lvh** [ztellman/aleph#204]
Right now, it doesn't appear there's support for TLS client certificates. I don't think this could be implemented using middleware; Netty's SslContext(Builder) does have support for it. SslContexts aren't a super great API, so I could see how that's not the primary way you'd want to expose that. However, I do think it's a _complete_ API, so it'd be good enough to at least make fancy TLS configs possible. Later (or a different library perhaps) could worry about giving that a nice Clojure API.

(I am volunteering to implement this.) Thoughts?

**Comment by ztellman** [comment]
Just so I understand: you're saying that this is currently possible with Aleph via the `:ssl-context` key, but it's a pain in the ass and Aleph should provide some helper functions to create an `SslContext` with a given certificate?  If so, I agree.  Go for it.

**Comment by lvh** [comment]
ssl-context is also a thing for clients? I could only find it in a map that gets passed to start-server.

**Comment by ztellman** [comment]
It can be set here: https://github.com/ztellman/aleph/blob/master/src/aleph/http.clj#L90

**Comment by lvh** [comment]
My bad. I was looking at http://ideolalia.com/aleph/aleph.http.html. Thanks!

**Comment by lvh** [comment]
(I may build that saner TLS API; when I do, I'll make sure that it produces SSL contexts and let you know to see if it would be something useful to contribute to aleph.)

**Comment by bhurlow** [comment]
@lvh @ztellman could either of you point me to an example of how to create an `ssl-context` for use with aleph? thnx!

**Comment by bhurlow** [comment]
specifically I'm trying to connect to a TLS secured docker daemon

**Comment by ztellman** [comment]
The expected object is described [here](http://netty.io/4.1/api/io/netty/handler/ssl/SslContext.html).  The examples of how this is used in Aleph are pretty trivial, but there can be found [here](https://github.com/ztellman/aleph/blob/master/src/aleph/netty.clj#L584-L594).

**Comment by bhurlow** [comment]
Aleph now recommends using the `SslContextBuilder` api. I've been able to connect to a tls enabled docker daemon with something like this:  

```
(defn server->ssl-context []
  (let [ca (str docker-cert-path "/ca.pem")
        cert (str docker-cert-path "/client-cert.pem")
        key (str docker-cert-path "/key.p8")]
    (.build
      (.keyManager
        (.trustManager
          (SslContextBuilder/forClient)
          (java.io.File. ca))
        (java.io.File. cert)
        (java.io.File. key)))))
```

@ztellman would you be open to adding a snippet to the docs to demonstrate this? would have saved me some java api hair-pulling

**Comment by ztellman** [comment]
Yes, I think having an example would be very helpful.  I'd also be willing to consider an `aleph.ssl` namespace.
