### ISSUE TITLE
Number of sockets open by a TCP connection

### ISSUE THREAD

**Issue by dpom** [ztellman/aleph#206]
My application implements a simple tcp client:

(ns qlib.device
  (:require
   [clojure.tools.logging :as log]
   [clj-stacktrace.repl :refer [pst-str]]
   [byte-streams :as bs]
   [manifold.stream :as s]
   [manifold.deferred :as dfr]
   [aleph.tcp :as tcp]
   ))

(defn connection-ok?
  [{:keys [connection] :as device}]
  (not (or (nil? @connection) (s/closed? @connection))))
  
(defn open-conn
  "Open connection handler."
  [t {:keys [device]}]
  (let [{:keys [id host port connection]}  device]
    (log/debugf "open-conn: id = %s time = %s" id (str t))
    (try
      (if-not (connection-ok? device)
        (dfr/on-realized (tcp/client {:host host :port port})
                         (fn [x]
                           (log/debugf "open-conn: id = %s connection ok" id)
                           (reset! connection x)
                           (s/consume (fn [msg] (dispatch-messages device msg)) x)
                           (reset-error! device)
                           )
                         (fn [x]
                           (log/debugf "open-conn: id = %s connection error" id)
                           (set-error! device :not-connected))))
      (catch Exception e
        (log/debugf "open-conn: id= %s error %s" id (pst-str e))
        (set-error! device (str e))))))

The TCP server has a limited sockets available and it seems that my TCP client opens each time 2 sockets. Is it true? If yes how could I limit them to only one?

I use:
clojure 1.6.0
aleph 0.4.0
manifold 0.1.0

**Comment by ztellman** [comment]
Please update to Aleph 0.4.1-beta3.  This is an issue with the inlining of `on-realized`, which has been fixed.

**Comment by dpom** [comment]
With this version works ok (only one socket is open)

Thank you
