### ISSUE TITLE
Deferred when request is closed

### ISSUE THREAD

**Issue by hadronzoo** [ztellman/aleph#207]
I have an `http-server` request handler that holds onto some resources until an action is complete. If the request is prematurely closed by the client, I'd like to release those resources. Is there a way to determine if a client has closed a request? It would be useful to have this event in a deferred.

**Comment by ztellman** [comment]
If you'd like to simply check if a connection is closed, you can do:

```clj
(-> req ^io.netty.channel.Channel .ch .isOpen)
```

If you'd like it as a deferred that's realized when the channel is closed, you can do:

```clj
(-> req ^io.netty.channel.Channel .ch .closeFuture aleph.netty/wrap-future)
```

Hope that helps.

**Comment by hadronzoo** [comment]
This is exactly what I was looking for. Thanks!
