### ISSUE TITLE
Host header is set incorrectly

### ISSUE THREAD

**Issue by SevereOverfl0w** [ztellman/aleph#210]
When making a http request against a server on a port, e.g. `@(http/get "http://localhost:3000")` the host header is set to "localhost" and should be "localhost:3000", see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

**Comment by ztellman** [comment]
The spec is a little ambiguous as to whether the port should be omitted if it's 80 (or possible 443).  It seems easiest to just always include it, any reason not to?

**Comment by SevereOverfl0w** [comment]
It _should_ be omitted if it's 80 (or 443 for https). I would worry that always including it may confuse some applications/web servers. I hear IIS is particularly bad in this regard, but don't speak from personal experience.

This is the http-kit implementation: https://github.com/http-kit/http-kit/blob/b495e5fb3c44ac792654bcf4157993613bc579cd/src/java/org/httpkit/HttpUtils.java#L247

This works because if a URI's port is not set, getPort() returns -1.
