### ISSUE TITLE
Timeout during performance testing with ab

### ISSUE THREAD

**Issue by artemyarulin** [ztellman/aleph#211]
Hi,

I decided to make couple of performance tests with aleph. I wrote very simple code:
``` clojure
(defn -main [& args]
   (http/start-server (constantly {:body "{}" :status 200}) {:port 7000})))
```
Then I decided to use [ab](https://httpd.apache.org/docs/2.2/programs/ab.html) tool: `ab -n 20000 -c 100 http://localhost:7000/`. In most of the cases test failed with timeout error like: 
```
apr_pollset_poll: The timeout specified has expired (70007)
Total of 16490 requests completed
```
If I run test with less number of requests sometimes it works just fine and sometimes I see something like that:
```
Server Software:        Aleph/0.4.0
Server Hostname:        localhost
Server Port:            7000

Document Path:          /
Document Length:        2 bytes

Concurrency Level:      100
Time taken for tests:   13.391 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      1170000 bytes
HTML transferred:       20000 bytes
Requests per second:    746.74 [#/sec] (mean)
Time per request:       133.915 [ms] (mean)
Time per request:       1.339 [ms] (mean, across all concurrent requests)
Transfer rate:          85.32 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  123 1137.1      8   11454
Processing:     0   11  21.6      9     259
Waiting:        0    9  20.7      8     258
Total:          0  134 1137.6     17   11474

Percentage of the requests served within a certain time (ms)
  50%     17
  66%     18
  75%     18
  80%     19
  90%     21
  95%     25
  98%    260
  99%  11433
 100%  11474 (longest request)
```
So, it looks like 1% of requests ended up with really big delay. Is this a GC going on?

**Comment by artemyarulin** [comment]
OK, I was advised to take [wrk](https://github.com/wg/wrk) tool, outputs looks better:

``` bash
$ wrk -t5 -c1000 -d60s "http://localhost:7000/" --latency
Running 1m test @ http://localhost:7000/check
  5 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    35.70ms  105.21ms   1.41s    90.98%
    Req/Sec     4.56k     4.58k   24.66k    84.88%
  Latency Distribution
     50%    1.31ms
     75%    4.08ms
     90%  123.86ms
     99%  516.43ms
  1141560 requests in 1.00m, 132.82MB read
  Socket errors: connect 754, read 10, write 0, timeout 0
Requests/sec:  18997.66
Transfer/sec:      2.21MB
```

But is there anything you can advice in order to improve aleph performance?

**Comment by artemyarulin** [comment]
Hm, looking for this [FrameworkBenchmarks project](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Clojure/aleph/hello/src/hello/handler.clj) I found out those lines:
``` clojure
(aleph.netty/leak-detector-level! :disabled)
(http/start-server handler {:port port, :executor :none})))
```
Does it make any different and should it be enabled by default if speed is important?

**Comment by ztellman** [comment]
If speed is of the utmost importance, then yes.  In most cases it won't
make too much of a difference, though.

The `ab` test timed out because you exhausted the ephemeral ports.  You'll
typically see this every 16384 requests, when the OS doesn't have any more
ports to allocate, and has to wait for previous connections to fully
expire.  You can work around this by specifying -k to use keepalive
connections, or to use the tuning parameters specified at the bottom of
this README: https://github.com/ztellman/aloha.

**Comment by artemyarulin** [comment]
Thank you! Exactly that - around 16k requests ab just hangs, thanks for the explanation. Out of scope of this project but aloha looks exactly what I need - how ready it is for production? And does it support async pipeline like Aleph with manifold.deferred?

**Comment by ztellman** [comment]
Don't use Aloha, at this point it's worse in every way than Aleph itself.  I'm not sure what your test environment is, but I've done local benchmarks where Aleph easily handled 300k qps, and on the techempower benchmarks it make it just over 1M qps.  You should make sure your JVM parameters are sane, including using `-server`, using G1GC, and having a non-default heap size.

**Comment by artemyarulin** [comment]
Thank you! I'll have a look on techempower JVM options
