### ISSUE TITLE
Aleph performance/blocking under heavy concurrent load.

### ISSUE THREAD

**Issue by bbsbb** [ztellman/aleph#213]
Hey Zach,

We've been trying to put aleph in production over the last week or so and it's been smooth sailing till today, when we started to do some stress testing and we're hitting a pretty heavy hurdle.
We're not quiet sure how to proceed, so decided to open an issue here and maybe pick your mind.
We are running aleph in front of manifold deferreds and as soon as we start doing stress testing on concurrent load we hit a lock in the server. We tried playing with different executors and settings (including :none), but the lock seems to be persistent. JVM profiling shows regular gc behavior and threads release and other jvm processes behave correctly, however, server stops processing requests (until d/timeout!).
Just wondering if you have an idea on how to approach this and maybe share.
Also, is aleph actually in production somewhere as far as you know? Thanks!

Edit: The lock happens in artificial tests and in production environment, both.

**Comment by ztellman** [comment]
Yes, at my last job I used Aleph to handle half a million queries/sec, and a variety of other companies use it in production.  I'm also told it's the basis for Atlassian's soon-to-be-released collaboration platform.

I'm not sure how you're benchmarking this, so it's hard to give concrete advice.  Usually this behavior is due to exhaustion of ephemeral ports (see this issue for the most recent example: https://github.com/ztellman/aleph/issues/211), but that may not be the case here.  What does the deferred represent here?  What is the server actually doing?  It's hard to give much advice without more information.

**Comment by bbsbb** [comment]
Hey,

Seems like we've found a likely culprit and it was an oversight on our side. We are heavily proxying requests, meaning we use an aleph client behind an aleph server, we've managed to tweak the server to a satisfactory performance(can be confirmed by raw requests), but our custom executor's thread pool had significantly higher thread limit than the one set for default response here https://github.com/ztellman/aleph/blob/master/src/aleph/http.clj#L75

Currently testing with a custom connection pool for requests and things are going better. I'll close it in a couple of hours if I managed to confirm this mismatch was indeed the reason for our pains.

**Comment by bbsbb** [comment]
So, we've managed to stabilize performance by creating a client connection pool of our own with a tweaked respone executor, a significantly higher max threads limit, connections-per-host and total-connections settings.
I believe it would be beneficial if the response-executor parameter gets added to the documentation and maybe the defaults should be either explicitly mentioned or adjusted to more sensible values. Thanks for the awesome library!

**Comment by ztellman** [comment]
To be clear, the 256 threads in the `response-executor` should only be exhausted if you're doing blocking operations later in the `d/chain` or `d/let-flow` once you've received a response.  Based on your original email, you seemed to indicate that your work was non-blocking.  If that's the case, more threads than 1-2x the number of cores should be superfluous.  It's possible that this may point to a problem with your approach.

However, you're completely right that documenting the response executor would be helpful.

**Comment by ztellman** [comment]
Unless you object, I'm going to close this issue.
