### ISSUE TITLE
Streaming bodies without memory leaks

### ISSUE THREAD

**Issue by martinraison** [ztellman/aleph#214]
Hi,

The application I'm working on requires handling HTTP request bodies as streams. Therefore the only option I have is to use `raw-stream?` to `true` in the server options. However, as you noted in the docs, it forces me to manage `ByteBuf` objects very carefully. In particular, I'm still seeing leaks even after adding a `(stream/map bs/to-byte-array s)` operation in the middleware and making sure the handler actually consumes the whole body.

Looking at the code for `aleph.http.server/ring-handler`, it seems that all I would need in order to make my life much easier would be, instead of using the `raw-stream?` option, to just be able to skip the transformation of the body into an input stream `(bs/to-input-stream body)`. Then all the `ByteBuf` transformation would be handled automatically. Any thoughts on this?

**Comment by ztellman** [comment]
By "leaks", you mean "this item was not released" warnings from Netty, or constant memory growth?  Mapping `bs/to-byte-array` should avoid the former, though it's possible that some might get dropped and require GC when a stream is closed (if so, that's a bug).

The alternative you're suggesting seems to be effectively mapping `bs/to-byte-array` over the raw stream, so maybe I'm misunderstanding what you're saying.

**Comment by martinraison** [comment]
I have both warnings from Netty + I observe a constant growth of weak references (which seem to be used internally in the manifold library).

I'm not super familiar with `aleph` internals, but the alternative I'm suggesting uses `ring-handler` instead of `raw-ring-handler`, which:
* is the default, so likely more battle-tested :)
* seems to have a pretty different logic overall. Just as an example, in `raw-ring-handler`, when handling the `LastHttpContent` message, `s/put!` is used instead of `netty/put!`, so I don't see where the message is released. Again I don't really know how all this works internally so I might be missing obvious things.

**Comment by ztellman** [comment]
The `WeakReferences` may grow, but they shouldn't be alive if you examine a heapdump.  If that's not true, please share the heapdump with me, so I can understand what's going on.

The `raw-ring-handler` should be fine as long as the stream it's putting into remains open.  If it's closed, I agree that it looks like there's potential for data to not be explicitly released.  The warnings are irritating, obviously, but aren't really cause for concern w.r.t. the stability of your process.  I'll definitely fix them, though.

The `ring-handler`, per the spec, uses an InputStream.  The `raw-ring-handler` has the benefit of being a lot simpler, so I don't think the solution is to simply make the `ring-handler` do everything.  Again, if you can provide evidence of a real memory leak, please do share it with me.

**Comment by martinraison** [comment]
Unless I'm mistaken, the existence of many `WeakReferences` in memory, whether alive or not, considerably increases the time of the G1GC remark phase (up to multiple seconds with about 25,000,000 references in memory). That's why I started hunting those down. I'm no GC expert so it's possible that something else would be causing this, but it seems like the most likely cause at this point.

I understand your reason for having `ring-handler` sticking to the ring spec. I only wish there was some abstraction that was slightly higher-level than `raw-ring-handler` (unless potential leaks in `raw-ring-handler` can be identified and fixed, and then mapping with `bs/to-byte-array` would be the only thing needed to be safe).

I'd love to share more details but I can't really send a heap dump (for confidentiality reasons). In the meantime I'll keep digging and update this thread if I find a solution that suits my needs.

Thanks for the help anyway!

**Comment by ztellman** [comment]
Okay, completely understand that a heapdump isn't possible here.  

That's a pretty large number of references, so I understand your concern.  A `WeakReference` is allocated basically whenever `manifold.stream/connect` is called, which is the underlying primitive for `map` and other operators.  As streams are closed, the expectation is that the underlying object will get collected, and the reference will get cleaned up.  If the streams are *not* being closed, or are still being referenced after they're closed, that would explain some of what you're seeing.  This can be easily investigated using YourKit or a similar application to dig into the heap dump.

I'll make the changes that I suspect will get rid of the Netty reference counting warnings, but I suspect that this and the WeakReference issue you're seeing are separate.  Let me know if you still suspect the underlying library as the cause once you've looked at the heap dump.

**Comment by ztellman** [comment]
By the way, I've pushed `0.4.1-SNAPSHOT` with a potential fix for the Netty warnings.

**Comment by ztellman** [comment]
Any updates on the heapdump?  If this is still an issue I should be thinking about, I'll leave it open, but otherwise I'm going to close it.

**Comment by martinraison** [comment]
The situation seems to be much better now so I haven't found the time to look at the issue more closely. We can close for now, I'll follow up if the issue comes up again. Thanks again :)
