### ISSUE TITLE
Determine the number of keepalive connections

### ISSUE THREAD

**Issue by hadronzoo** [ztellman/aleph#215]
Is it possible to determine the of clients connected to Aleph—not just those actively making requests, but also those that have established a keepalive connection?

**Comment by hadronzoo** [comment]
I solved this by [creating a `ChannelDuplexHandler`](https://github.com/orgsync/arion/blob/36e2f9bdd104f4209cc0642a0ea33d7e5741c8b9/src/arion/api.clj#L94-L103):

```clojure
(def connection-timer-key (AttributeKey/valueOf "connection_duration"))

(defn ^ChannelDuplexHandler connection-tracker [conn-count conn-timer]
  (proxy [ChannelDuplexHandler] []
    (channelActive [ctx]
      (let [attr (.attr ctx connection-timer-key)]
        (.set attr (timer/start conn-timer))
        (counter/inc! conn-count)))
    (channelInactive [ctx]
      (let [attr (.attr ctx connection-timer-key)]
        (counter/dec! conn-count)
        (timer/stop (.get attr))))))
```

and [inserting it into the pipeline](https://github.com/orgsync/arion/blob/36e2f9bdd104f4209cc0642a0ea33d7e5741c8b9/src/arion/api.clj#L125-L129):

```clojure
(fn [^ChannelPipeline pipeline]
  (doto pipeline
    (.addFirst "conn-state" (connection-tracker conn-count conn-timer))))
```

**Comment by ztellman** [comment]
This is what I was going to suggest when I had the time to reply, it's the best/only approach I can think of.

**Comment by hadronzoo** [comment]
Thank you for taking a look at this.
