### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by mping** [ztellman/aleph#216]
I'm doing a simple http server:

```
(defn hello-world-handler
  "A basic Ring handler which immediately returns 'hello world'"
  [req start end]
  {:status 200
   :headers {"content-type" "text/plain"}
   :body (format "start: %s, end %s" start (now))})

(defn delayed-hello-world-handler
  [req]
  (let [start (now)]
    (d/timeout!
     (d/deferred)
     2500
     (hello-world-handler req start (now) ))))

(def handler
  (compojure/routes
   (GET "/" [] delayed-hello-world-handler)
   (route/not-found "No such page.")))
```

But when I pound it with `wrk` I get the following error:

`wrk -R 50000 -d 5s -t 2 -c 1000 http://localhost:8888`

```
Feb 24, 2016 8:54:15 AM clojure.tools.logging$eval420$fn__424 invoke
SEVERE: error in deferred handler
java.util.concurrent.RejectedExecutionException
	at io.aleph.dirigiste.Executor.execute(Executor.java:332)
	at manifold.deferred.Deferred$fn__10966.invoke(deferred.clj:396)
	at manifold.deferred.Deferred.success(deferred.clj:396)
	at manifold.deferred$success_BANG_.invokeStatic(deferred.clj:243)
	at manifold.deferred$success_BANG_.invoke(deferred.clj:240)
	at manifold.deferred$timeout_BANG_$fn__11238.invoke(deferred.clj:1114)
	at manifold.time$in$f__10680.invoke(time.clj:231)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
...
```

I can't figure out if I'm doing something wrong or its an aleph issue

**Comment by Gonzih** [comment]
To me it looks like you are consuming your executor pool because result of `(hello-world-handler req start (now) )` will be only returned after 2500ms timeout. But I might be completely wrong. I would assume that since you use deferred you should not consume threads.

**Comment by mping** [comment]
Actually AFAIK the deferred timeout call is executed *imediately* but the deferred ensures it only returns after 2500ms, thats why the timestamps have the same seconds on the response.

**Comment by ztellman** [comment]
It's because you're missing this: https://github.com/ztellman/aleph/blob/master/examples/src/aleph/examples/http.clj#L50-L52.  Compojure blocks on `IDeref` objects by default.  I've just realized this update to the example docs was never pushed to aleph.io, I'll fix that.

**Comment by mping** [comment]
Thanks!

**Comment by mping** [comment]
To be clear, the Protocol makes sure it doesn't block on deferreds, but I still see the same timestamp. I'm guessing my understanding on how the deferred works is a little bit off.

**Comment by Gonzih** [comment]
You evaluate (now) before you call timeout.

To be clear, the Protocol makes sure it doesn't block on deferreds, but I
still see the same timestamp. I'm guessing my understanding on how the
deferred works is a little bit off.

—
Reply to this email directly or view it on GitHub
<https://github.com/ztellman/aleph/issues/216#issuecomment-188744024>.

**Comment by mping** [comment]
@Gonzih I didn't get your comment, I have two `(now)` calls, do you mean that in the line `(hello-world-handler req start (now) )` thats evaluated before the timeout? I am expecting `start` to be different from `now` at this time but like I said maybe I need to understand when the deferred is actually evaluated.

**Comment by Gonzih** [comment]
Both now calls are evaluated almost at the same time. Last argument to the timeout! is a default value. timeout! a function, not a macro. It will just evaluate your arguments.

**Comment by mping** [comment]
Duh. My bad. I was *thinking* I was passing a function for later evaluation, but I'm actually evaluating it.
Thanks.
