### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory errors

### ISSUE THREAD

**Issue by malcolmsparks** [ztellman/aleph#224]
Related to https://github.com/juxt/yada/issues/75

we're seeing 

    java.lang.OutOfMemoryError: Direct buffer memory

and 

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 3653632 bytes for committing reserved memory.
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000ff815000, 3653632, 0) failed; error='Cannot allocate memory' (errno=12)
# An error report file with more information is saved as:
```

when streaming request bodies via manifold from aleph.

I'm using `manifold.stream/reduce` over the incoming stream (with raw-streams?set to true). Each buffer is subject to a `byte-streams/to-byte-buffer` which I thought decremented the reference count.

Versions are:

```clojure
[aleph "0.4.1-beta5"]
[byte-streams "0.2.1"]
[manifold "0.1.2"]
```

I've been printing out the refCnt field of the ByteBufs from the stream and they appear quite high (3-6) but I'm not sure what is 'normal' here. Could this be a bug in Netty?

Also, JVM options are:

```
:jvm-opts ["-Xms1g" "-Xmx1g" "-server" "-Dio.netty.leakDetectionLevel=advanced"]
```

But I'm not seeing any leak detection messages from Netty's leak detector.

I'm a bit stumped. My current strategy is to replace netty+aleph with xnio+undertow to prove that the issue is not in manifold, but this might be misguided.

**Comment by malcolmsparks** [comment]
I will try to create a smaller failing test that only uses manifold, aleph and netty.

**Comment by ztellman** [comment]
As I'm fairly sure this isn't an Aleph issue, I'm inclined to close this.  Any objections?

**Comment by malcolmsparks** [comment]
Yes, please close this issue.

For reference, the following did fix the issue.

    -Dio.netty.allocator.numDirectArenas=0

However, the performance is then reduced substantially. This needs more investigation but directly with the Netty team.
