### ISSUE TITLE
Netty thread-pool leak

### ISSUE THREAD

**Issue by thheller** [ztellman/aleph#227]
Even after https://github.com/ztellman/aleph/commit/b72db22db6ccd270782ddab663d7662510a08be4 I'm still encountering a leak somehow.

In addition to `.close`ing the server instance I do

```clojure
(defn shutdown-aleph []
  (when (realized? netty/epoll-client-group)
    (.shutdown @netty/epoll-client-group))
  (when (realized? netty/nio-client-group)
    (.shutdown @netty/nio-client-group))

  (.shutdown aleph/default-connection-pool))
```

After all that there is a lingering non-daemon "nioEventLoopGroup" thread pool alive [1] and keeping the JVM from fully shutting down. I don't like calling `(System/exit)` so I'd prefer to find the leak. Apart from an obvious leak in `aleph.udp/socket` (the group `g` is never reachable to be shutdown) I can't find anything else. Since I don't use the `aleph.udp` I'm out of ideas where to look.

Maybe you have an idea what might be causing this leak?

[1] https://gist.github.com/thheller/948a7c5fff8f1db9b929#file-thread-dump-txt-L189-L490

**Comment by ztellman** [comment]
I'll take a look.  I'm probably going to make all the event loops use daemon threads, but I'll see if I can figure out why the threads aren't shutting down properly, too.

**Comment by kmrozek-siili** [comment]
The server doesn't block java process after this fix. When I create server with http/start-server in the main function and it exits main functions, it finishes the java process immediately. How can I block the process than?

**Comment by thheller** [comment]
```clojure
(with-open [server (start-the-server)]
  (loop []
    (when-not (some-exit-condition?)
      (Thread/sleep 500)
      (recur))
    ))
```

Basically you loop the main thread until some exit condition is reached. If you don't want an exit condition just loop forever or use that thread to do something useful.
