### ISSUE TITLE
Question about aleph.http

### ISSUE THREAD

**Issue by emiln** [ztellman/aleph#233]
Hi, ztellman.

I'm writing my very first project using aleph, and I've stumbled upon something that feels like I'm rubbing the library the wrong way. I hope you can help me.

Let's say I've required `[manifold.deferred :as d]`, `[aleph.http :as h]`, and `[byte-streams :as bs]` in the following and that I want to call `h/get` and take action based on the HTTP status code returned. It could be 200, 400, or a number of other status codes, and even in the case of a non-successful (non-200) response, I still want to know about the response, its status code, body, etc.

If I try the following, I get no output at all:

```clojure
(d/chain
  (h/get "URL_PRODUCING_STATUS_400")
  :body
  bs/to-string
  prn)
```

The reason is probably that the GET request raises an exception:

```clojure
@(h/get "URL_PRODUCING_STATUS_400")
#=> clojure.lang.ExceptionInfo: status: 400
```

I could use a try-catch to get the info from the Exception:

```clojure
(try
  @(h/get "URL_PRODUCING_STATUS_400")
  (catch Exception e
    (:status (.data e))))
```

I just can not help feeling that this is all rather awkward. Is there a straightforward way to always get the status code and body of a request, such that it never throws an Exception?

Best regards,
Emil

**Comment by ztellman** [comment]
Yes, specify `:throw-exceptions?` to be false in `h/get`.  This default behavior, and parameter, are taken from clj-http, which provides more detail at https://github.com/dakrone/clj-http.

**Comment by emiln** [comment]
Ah, thanks a lot! In retrospect I see how that follows from

>>> For HTTP client requests, Aleph models itself after clj-http, except that every request immediately returns a Manifold deferred representing the response.

but it might be worth being explicit about referring to their documentation if the APIs are literally identical.

That's just a suggestion, though. My problem is fully solved, so thanks again.
