### ISSUE TITLE
epoll + SO_REUSEPORT

### ISSUE THREAD

**Issue by NoamB** [ztellman/aleph#237]
Hi,

Won't epoll + SO_REUSEPORT (accepting on same port with many threads) help boost incoming rate of packets? I have bumped into this while trying to build a fast UDP server. Currently I am getting 12K/s using s/take from a udp socket, with the default NIO implementation, on a 16 core VM in Azure.

Thanks.

**Comment by ztellman** [comment]
Netty currently doesn't support epoll for UDP. What level of throughput are
you trying to achieve?

**Comment by NoamB** [comment]
The higher the better... :)
If I can get to 100K/s per VM that will be very good. Anything I can do to push performance up?

**Comment by ztellman** [comment]
Hmm, this issue seems to suggest I'm wrong about epoll not being supported for UDP: https://github.com/netty/netty/issues/1706.  Let me add the wiring necessary to let you access the epoll implementation, and we'll see.

**Comment by NoamB** [comment]
That's awesome, thank you!

Found this, might help you:
http://marrachem.blogspot.co.il/2014/09/multi-threaded-udp-server-with-netty-on.html

To make it work seems you need to bind the same port multiple times with different threads.

**Comment by ztellman** [comment]
This should be supported in `master`, and you can set SO_REUSEPORT using `bootstrap-transform`.

**Comment by NoamB** [comment]
I can confirm it is working, i.e. I can bind multiple sockets on same port and traffic from different IPs spreads between different sockets. Still checking what is the performance gain, but as far as I am concerned the issue is resolved. Thank you for the quick work!

Any release planned soon to clojars?

**Comment by ztellman** [comment]
Yes, I'm in the middle of packing up my apartment right now, but soon.

**Comment by ztellman** [comment]
This is out in `0.4.2-alpha3`.

**Comment by NoamB** [comment]
(If anyone is interested)
Performance is really good :) I have crossed the 150K packets/sec mark, using only 4 ports, so this will go up even more!

Thanks again.
