### ISSUE TITLE
http server dies immediately

### ISSUE THREAD

**Issue by dustinconrad** [ztellman/aleph#238]
I feel like I must be doing something wrong here.  I have an extremely simple project.

project.clj
```clojure
(defproject aleph-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [ring"1.4.0"]
                 [aleph "0.4.1"]]
  :main ^:skip-aot aleph-test.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```
aleph-test.core
```clojure
(ns aleph-test.core
  (:gen-class)
  (:require [aleph.http :as http]
            [ring.adapter.jetty :as jetty]))

(defn handler [req]
  {:status 200
   :headers {"content-type" "text/plain"}
   :body "hello!"})

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (if (= "aleph" (first args))
    (http/start-server handler {:port 8088})
    (jetty/run-jetty handler {:port 8089})))
```
when I do lein run aleph, the server pretty much exits immediately.  for jetty it works as expected.
```bash
➜  aleph-test lein run aleph
2016-04-26 23:41:14.922:INFO::main: Logging initialized @3070ms
```

**Comment by ztellman** [comment]
Maybe I'm missing something about your example, but it looks like you're starting two different servers on the same port.  Are you commenting out one before you run this?

**Comment by dustinconrad** [comment]
Hello Zach,
I've updated the example.  The intent is to start either a jetty or an aleph server.  I also just changed it so there shouldn't be a port conflict if I do somehow miraculously start both servers.

**Comment by dustinconrad** [comment]
Here is the minimal repro in it's entirety, hopefully this clears up any confusion:
project.clj - same first post.

aleph-test.core
```clojure
(ns aleph-test.core
  (:gen-class)
  (:require [aleph.http :as http]
            [ring.adapter.jetty :as jetty]))

(defn handler [req]
  {:status 200
   :headers {"content-type" "text/plain"}
   :body "hello!"})

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (http/start-server handler {:port 8088}))
```

**Comment by ztellman** [comment]
This is just due to the fact that all the threads used by the server are daemon threads, and don't prevent the process from closing.  If you add `@(promise)` to the bottom or something like that, it won't exit.

**Comment by dustinconrad** [comment]
That makes sense, thanks for the quick replies Zach.

**Comment by ztellman** [comment]
No worries, I can see why it's confusing.  I've just committed a change that lets you deref the value returned by `start-server` so that you can block until it's closed, since that seems like the easiest way to get around this.

**Comment by tangrammer** [comment]
Hi guys, 

maybe it could be good to have this !how to run" in the readme, it took 2 hour to reach this page 😄 

thanks!

**Comment by arichiardi** [comment]
Is the deref on the returned value still the correct solution to this?

**Comment by ztellman** [comment]
Sorry, no, it was pointed out that had weird consequences in the REPL. The
new method is aleph.netty/wait-for-close.

**Comment by arichiardi** [comment]
Perfect thank you!

-ar

**Comment by arichiardi** [comment]
I ended up using Apache Commons Daemon in my particular backend and I will add the option in [lambone](https://github.com/Lambda-X/lambone) as well.
Would setting the Thread Pool as non-daemon solve the issue without "waiting" by the way?
I am not sure about that because for instance Jetty allows to have a non-daemon thread pool but there might be a moment in time where there are no active threads anyways and the JVM exits.

**Comment by arichiardi** [comment]
I also tried `wait-for-close` and it works but of course locking the Thread you are calling it on. This might or might not be a problem. It is tricky because as soon as the main thread exits AND no non-daemon threads are RUNNING (not even WAITING), then the JVM is shut down.

**Comment by ztellman** [comment]
That's sort of the idea.  The main thread can simply wait on the server to
close.

**Comment by fmnoise** [comment]
just found that version 0.4.4 works normal without explicit main thread locking 
@ztellman is that expected?
