### ISSUE TITLE
Documentation issues?

### ISSUE THREAD

**Issue by DrawnWren** [ztellman/aleph#243]
I'm getting some errors when trying to follow links in documentation. 
From this page, http://aleph.io/examples/literate.html#aleph.examples.http the aleph.http namespace documentation link (to this -> http://ideolalia.com/aleph/aleph.http.html) leads to a 'no such thing' page.

Is the examples documentation the only doc page or is there another doc page that I'm missing?

**Comment by DrawnWren** [comment]
Found my mistake. I think it's meant to go here: http://aleph.io/aleph/http.html

**Comment by martinklepsch** [comment]
This can be closed I believe.
