### ISSUE TITLE
Running Netty server object unprintable

### ISSUE THREAD

**Issue by cemerick** [ztellman/aleph#246]
As of 8d11ad75, the object returned by `aleph.http/start-server` cannot be printed (usually at the REPL, but ofc a possibility in other contexts) without blocking, until the server is closed. Not a _problem_, but perhaps surprising, and maybe tricky to track down if e.g. someone happens to put a server object in a map or something which then gets logged.

I see a couple of options. An `IPending` impl could be added to the reified object, like:

```clojure
clojure.lang.IPending
(isRealized [_]
  (and (-> ch .closeFuture .isDone)
    (-> group .terminationFuture .isDone)))
```

Gets the job done, but not really in the spirit of `IPending`, `realized?`, etc. The more principled and functional approach would be to swap out `IDeref` for `IBlockingDeref`; this would fix the printing problem, and also let (uh, force?) people using the deref-to-wait-for-server-close feature avail themselves of a timeout. The only downside AFAICT is that you couldn't just `@server` to wait. The equivalent would be `(deref server Long/MAX_VALUE nil)`.

**Comment by ztellman** [comment]
Balls, I forgot about auto deref on print. Let me think about this a bit
more.
