### ISSUE TITLE
Latency/Blocking with 'aleph.flow/fixed-thread-executor' 

### ISSUE THREAD

**Issue by xsc** [ztellman/aleph#249]
Hey there,

I adjusted my test server at https://github.com/xsc/aleph-stream-testcase to expose a `/proxy` endpoint which fetches `http://google.com` and returns its HTML as a String in `:body`. Now I observed significant problems when not using the server's default executor, but a fixed-size one ([here](https://github.com/xsc/aleph-stream-testcase/blob/master/src/aleph_stream_testcase/core.clj#L45-46)):

```clojure
(aleph.flow/fixed-thread-executor 4)
```

The weird part here is that the following things only concern the `/proxy` endpoint, not the others - and none of them appear if using the default `utilization-executor`.

### Initial Delay

First thing I noticed is that the server will accept one connection immediately, but the other three only after ~10s of delay:

```
$ httperf --num-conns=4 --rate=4 --num-calls=100 --port=9877 --uri=/proxy
```

```
$ lein run -m aleph-stream-testcase.core fixed-thread
server is running ...
[request] 1463492234227 ...
[request] 1463492243524 ...
[request] 1463492243526 ...
[request] 1463492243528 ...
```

This can actually be fixed by supplying `:initial-thread-count 4` to `aleph.flow/fixed-thread-executor` but it still seems reasonable for a fixed-size thread pool to initially already have its fixed size. (This would then be an issue in manifold and I'll gladly open it there or provide a patch if desired.)

### Blocking

Occupying all of the server's (!) threads at once seems to block the internal HTTP client (!). The following commands work fine, i.e. the server responds as expected:

```
$ httperf --num-conns=3 --rate=3 --num-calls=100 --port=9877 --uri=/proxy
$ httperf --num-conns=2 --rate=8 --num-calls=100 --port=9877 --uri=/proxy
$ httperf --num-conns=1 --rate=8 --num-calls=100 --port=9877 --uri=/proxy
$ httperf --num-conns=8 --rate=8 --num-calls=100 --port=9877 --uri=/bytes
```

Now, once I use as many or more connections simultaneously as there are threads in the pool, the server will start to block indefinitely at some point:

```
$ httperf --num-conns=4 --rate=8 --num-calls=100 --port=9877 --uri=/proxy
```

If I increase the pool size to 8, everything up to 7 connections will work fine, but starting with the 8th one the same problem appears. Again, the `/bytes` endpoint can be bombarded without problem, just like the `utilization-executor` - only the `fixed-thread-executor` causes this.

### Conclusion

Seeing these symptoms it seems to me that aleph client and server are interacting in one way or another - but I might be misinterpreting the facts, as I don't see any reason why they should be sharing any resources.

Let me know if you need any more information!
Yannick

__Update (20.05.2016):__ Going through other issues, the behaviour outlined in #213 seems to match the description here.

**Comment by xsc** [comment]
So... Passing `{:onto? false}` to `fixed-thread-executor` fixes the deadlock - meaning that the HTTP client indeed runs its requests (or the response processing) on `manifold.executor/executor-thread-local`? I'm still trying to figure out where exactly this happens, though.

This at least needs additional documentation, I think.

**Comment by ztellman** [comment]
Hmmm, the processing should be taking place on the response processing pool, but calling `slurp` may be having some weird effects.  Out of curiosity, why not just pass the body through unchanged?  Is this an accurate portrayal of something you're doing in production?

**Comment by xsc** [comment]
> Out of curiosity, why not just pass the body through unchanged?

Passing `:body` directly does not change the behaviour, it seems.

> Is this an accurate portrayal of something you're doing in production?

It is. We're using an HTTP service (accessed using aleph's HTTP client) to aggregate some data for another, user-facing aleph server, previously backed by http-kit. When switching to aleph we wanted to maintain the general behaviour, so we opted for a fixed-size thread pool. (Setting `:onto?` to `false` seems to fix the issue in that system, btw.)

**Comment by ztellman** [comment]
Yeah, that means it's jumping threads, but I'm not sure where exactly.  I'll look into it.

**Comment by ztellman** [comment]
This is due to the request middleware being evaluated on the server thread pool, rather than the response executor, which creates a deadlock when the server handlers block up the entire pool.  I'm not entirely sure how I'd like to fix this, though.  Updates to come.

**Comment by ztellman** [comment]
Sorry for the delay in getting this solved, please let me know if you're seeing any hint of this remaining.
