### ISSUE TITLE
WebSocket does not receive incoming messages after a few restarts

### ISSUE THREAD

**Issue by lgrapenthin** [ztellman/aleph#250]
My dev client aggressively tries to create a new websocket connection after a websocket connection terminates. This happens when I restart the dev server (by calling .close and then creating a new instance per start-server on the same port).

After about ten server resets this creates a websocket connection that doesn't receive any messages. Server puts succeeds, they reach the client.  

Making the client wait 1000ms before creating a new connection solves the problem.
However, I consider it a bug because the server should only create working websocket connections.

**Comment by ztellman** [comment]
Yes, I'd agree this seems like a bug, though I'm not sure where it's originating.  Would it be possible for you to provide a simple reproducing example?

**Comment by lgrapenthin** [comment]
This should run forever. Instead it outputs:

Client connection error, restarting client
Client put ping
server received  ping , restarting server
Client connection closed, restarting client
Client connection error, restarting client
Client put ping
server received  ping , restarting server
Client connection closed, restarting client
Client connection error, restarting client
Client connection error, restarting client
Client connection error, restarting client
Client put ping

> (ns aleph-bug.core
>   (:require [aleph.http :as http]
>             [manifold.stream :as s]
>             [manifold.deferred :as df]))
> 
> (defn run-client []
>   (let [url "ws://localhost:8080"
>         connection (http/websocket-client url)]
>     (df/catch
>         (df/let-flow [connection (df/timeout! (df/catch (http/websocket-client url)
>                                                   (constantly nil))
>                                               100
>                                               nil)]
>           (if connection
>             (do (s/put! connection "ping")
>                 (println "Client put ping")
>                 (s/on-closed connection
>                              (fn []
>                                (println "Client connection closed, restarting client")
>                                (run-client))))
>             (do
>               (println "Client connection error, restarting client")
>               (run-client))))
>         (fn [error]
>           (println "client error:" error)))))
> (def server (atom nil))
> 
> (defn run-server []
>   (let [do-restart (promise)
>         server (reset!
>                 server
>                 (http/start-server
>                  (fn [req]
>                    (df/catch
>                        (df/let-flow [connection (df/catch (http/websocket-connection req)
>                                                     (constantly nil))]
>                          (if connection
>                            (s/consume (fn [x]
>                                         (println "server received " x ", restarting server")
>                                         (do-restart))
>                                       connection)
>                            {:status 400
>                             :headers {"content-type" "application/text"}
>                             :body "Expected a websocket request."}))
>                        (fn [error]
>                          (println "server error:" error))))
>                  {:port 8080}))
>         _ (deliver do-restart
>                    (fn []
>                      (.close server)
>                      (run-server)))]))

**Comment by sniperliu** [comment]
I encounter similar issue. 
I am running 5 web socket client on 5 threads.
when the server reboot, all these 5 threads will re-connect to the server.
If the connectings' interval is more than 1 sec, most of time it could connect the server. but if they happened within 1 sec, @(websocket-client) will stuck.

In the logs, i could see handshake happened, but not preceed.
20/01/2017 07:09:29.038 [aleph-netty-client-event-pool-1-1]  DEBUG i.n.h.c.h.w.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: wkXfxwPVTa+rr4BINGeS3g==, expected response: PcKG2rrttJSdkow1Z1UrPAep2NM=
20/01/2017 07:09:29.038 [aleph-netty-client-event-pool-1-1]  DEBUG i.n.h.c.h.w.WebSocketClientHandshaker13 - WebSocket version 13 client handshake key: wkXfxwPVTa+rr4BINGeS3g==, expected response: PcKG2rrttJSdkow1Z1UrPAep2NM=
20/01/2017 07:09:29.059 [aleph-netty-client-event-pool-1-1]  DEBUG io.netty.handler.ssl.SslHandler - [id: 0x347c3c66, L:/10.140.0.4:45660 - R:ws.dev.my-doc.com/130.211.36.179:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
20/01/2017 07:09:29.059 [aleph-netty-client-event-pool-1-1]  DEBUG io.netty.handler.ssl.SslHandler - [id: 0x347c3c66, L:/10.140.0.4:45660 - R:ws.dev.my-doc.com/130.211.36.179:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

**Comment by ztellman** [comment]
Thanks for the report, I'll see what I can do to reproduce this.

**Comment by ztellman** [comment]
I'm unable to reproduce this on the latest Netty release, so I'm going call this fixed.
