### ISSUE TITLE
Let-flow in ring.session?

### ISSUE THREAD

**Issue by arichiardi** [ztellman/aleph#254]
Hello Zach,
I was reading the README and specifically:

> This feature may not play nicely with Ring middleware which modifies the response, but this can be easily fixed by reimplementing the middleware using Manifold's let-flow operator.

I have some problem with [`ring.session`](https://github.com/ring-clojure/ring/issues/250) and I was wondering if I need to use `let-flow` in a wrapping middleware before `ring.session`.

Sorry, this is not really a bug, more like a usage request, but I am willing to edit the README with an example in exchange :smile:

**Comment by ztellman** [comment]
Sure, if this is the current `wrap-session` middleware:

```clj
(defn wrap-session
  ([handler]
     (wrap-session handler {}))
  ([handler options]
     (let [options (session-options options)]
       (fn [request]
         (let [new-request (session-request request options)]
           (-> (handler new-request)
               (session-response new-request options)))))))
```

then you'd want to rewrite it as something like:

```clj
(defn wrap-session
  ([handler]
     (wrap-session handler {}))
  ([handler options]
     (let [options (session-options options)]
       (fn [request]
         (let [new-request (session-request request options)]
           (d/let-flow [response (handle new-request)]
             (sessions-response response new-request options)))))))
```

Note that this is not tested.

**Comment by arichiardi** [comment]
Thanks @ztellman I will test it, I was thinking exactly about this implementation.

**Comment by arichiardi** [comment]
One thing, `session-options` is not public so this cannot work with that at the moment, also, I have for some reason a `nil` for the some cookie (from the input request [here](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session.clj#L27)) but I will investigate what happens ok?
