### ISSUE TITLE
HTTP post requests with JSON content type not generating JSON body

### ISSUE THREAD

**Issue by solatis** [ztellman/aleph#257]
It seems that I've hit a bug when trying to send a post request with form-params as a JSON body. For clj-http, this is the way that this should be done is like this:

`(client/post "http://site.com" {:form-params {:foo "bar"} :content-type :json})`

However, when inspecting Aleph's client middleware, it appears as if there is no logic that actually generates a json body:

```
      (let [content-type (get req :content-type :x-www-form-urlencoded)]
        (-> req
          (dissoc
            :form-params)
          (assoc
            :content-type (content-type-value content-type)
            :body (generate-query-string
                    (nest-params form-params)
                    (content-type-value content-type)))))
```

As you can see, it uses `generate-query-string` to generate the body, which, of course, is invalid JSON. 

If this bug is indeed confirmed, I would be willing to write a fix for this.

**Comment by ztellman** [comment]
All of the client middleware is lifted directly from clj-http, but it's possible I've fallen behind since I did my copying.  Can you point me to the code in clj-http which performs this?

**Comment by solatis** [comment]
This is the clj-http code where it's done:

https://github.com/dakrone/clj-http/blob/master/src/clj_http/client.clj#L409

I think, however, that Aleph's code is quite different from this, and might need another approach.

**Comment by solatis** [comment]
@ztellman when I'm tackling the multipart issue, I could also tackle this issue as well if you want. Seems like an easy enough patch. I'm thinking about doing a multimethod for generating the body for different values of `:content-type`.

**Comment by ztellman** [comment]
Please feel free.  I haven't looked at this very carefully, but `aleph.http.client-middleware` is copy/pasted code from clj-http which has been very lightly modified.  I suspect a fix for this is just figuring out what new code needs to be copy/pasted into that namespace.

**Comment by solatis** [comment]
This is the logic in clj-http that does the body context type coercing, which pretty much follows the multimethod approach:

https://github.com/dakrone/clj-http/blob/master/src/clj_http/client.clj#L756

As far as I can see, this indeed integrates really well into aleph's http client middleware. Expect a PR soon!

**Comment by JarredLHumphrey** [comment]
@solatis This was resolved by https://github.com/ztellman/aleph/pull/258 , right?

**Comment by solatis** [comment]
@JarredLHumphrey Correct, and as such this issue can be closed.
