### ISSUE TITLE
TCP Examples are not working

### ISSUE THREAD

**Issue by bcambel** [ztellman/aleph#260]
Can you confirm that the TCP examples are working ? 

In my case, the client seems to unable to connect to the server, although the put command returns true, when you try to take the value, it halts; and no connection is established on the server side. 

Branch 0.4.2-Alpha6

Thanks

**Comment by ztellman** [comment]
It works for me.  If the `put!` command is succeeding, that's because you have a stream, which means that a connection has been established.  What makes you think there's no connection on the server side?

**Comment by bcambel** [comment]
That's correct. I do see the client do able to connect to the server. Somewhere along the coding, it stuck, anyways I do now see the client connection to server.

Here is the repo that I have created to test out the code. I did small name refactoring, because `s` was used extensively in your example. 

https://github.com/bcambel/alp

Thanks for your time.

**Comment by bcambel** [comment]
also if you check out the https://github.com/bcambel/alp/blob/master/src/alp/raw.clj which works perfectly.

**Comment by ztellman** [comment]
Hi, I'm sorry I didn't check back on this.  I'm unclear on what exactly you're seeing here.  The examples, as-is, work fine for me.  Can you clarify how you're getting stuck?
