### ISSUE TITLE
no such var: executor

### ISSUE THREAD

**Issue by qsys** [ztellman/aleph#261]
In a very simple setup, I try to start an aleph server without quitting immediately. This has been addressed in [this issue](https://github.com/ztellman/aleph/issues/238). However, when I try this solution, I have to use aleph 0.4.2-alpha6, and when I do so, I get this error when starting:
```
clojure.lang.ExceptionInfo: No such var: executor/with-executor
    data: {:file "aleph/http.clj", :line 203}
java.lang.RuntimeException: No such var: executor/with-executor
```
My code:

```
(ns myproject
  (:require [aleph.http :as http]
            [bidi.ring :refer [make-handler} :as bidi]
            ...)
...
(defn -main [& args]
  (http/start-server
    (bidi/make-handler api)
    {:port 3000}))
```

**Comment by ztellman** [comment]
Are you explicitly specifying your own version of Manifold?  That macro is only available in the latest version.

**Comment by qsys** [comment]
yes... well, I use yada, and manifold is included in that one. I excluded `[manifold "0.1.4"]` from yada and added `[manifold "0.1.5"]`. Seems to work now... Thx!

```
  :dependencies ...
    [yada "1.1.29" :exclusions [manifold]]
    [manifold "0.1.5"]
```
