### ISSUE TITLE
Indefinite blocking on http client large document requests

### ISSUE THREAD

**Issue by solatis** [ztellman/aleph#268]
When coercing to json, the client middleware calls `bs/to-byte-array`, which blocks indefinitely when requesting a large document.

Case in point:

    @(http/get "http://jsonplaceholder.typicode.com/posts/1" {:as :json})
    -> returns immediately
    
    @(http/get "http://jsonplaceholder.typicode.com/comments" {:as :json})
    -> blocks indefinitely

After a debug session, I have concluded that this is correlated whether Netty returns `HttpContent` versus `HttpResponse`; in other words, this happens with chunked transfers. I have time available to debug this issue tomorrow, but I could use some help figuring this issue out, since it touches Aleph's internals quite a lot.

**Comment by ztellman** [comment]
What version of Aleph are you using?

**Comment by solatis** [comment]
I'm using the current master branch.

**Comment by ztellman** [comment]
Okay, this appears to be an issue with `bs/to-byte-array` being called on the wrong thread, which deadlocks Netty.  I'm going to merge your changes, and then make sure the coercion happens on the proper threads.

**Comment by solatis** [comment]
That is exactly what I figured, that it probably is a single worker thread blocking on `bs/to-byte-array`, which doesn't get fed any new data, because there is only one worker thread.

**Comment by JarredLHumphrey** [comment]
+1 ran into this while doing some testing today. Happy to help out if its needed!

**Comment by solatis** [comment]
@ztellman Thanks for fixing this! Could you push the current master/alpha7 to clojars?

**Comment by JarredLHumphrey** [comment]
Awesome thanks @ztellman

**Comment by ztellman** [comment]
I've pushed 0.4.2-alpha8 to clojars.
