### ISSUE TITLE
`(s/close! ..)` on batched websocket causes hang

### ISSUE THREAD

**Issue by vspinu** [ztellman/aleph#269]
I have just started looking at the library, so I might be doing nonesense. I am not even sure this is manifold or aleph issue.  The last line of the following causes a hang:

```clj
;; create a batched source from an open websocket
(def b-socket (s/batch 100 socket))
(s/consume #(prn (count %)) b-socket)
(s/close! b-socket)
 ```

This is Clojure 1.8.0, Java 1.8.0_74, aleph "0.4.1", manifold "0.1.5"

**Comment by ztellman** [comment]
Hi, can you target Manifold "0.1.6-alpha1", and tell me if the issue persists?

**Comment by vspinu** [comment]
Just tried it. Works as expected. Thanks!
