### ISSUE TITLE
close codes for websocket client?

### ISSUE THREAD

**Issue by vspinu** [ztellman/aleph#270]
How to get more info when server closes websocket connection. Particularly, is there a way to retrieve the [close code](https://tools.ietf.org/html/rfc6455#section-7.4.1)? 

Thanks.

**Comment by ztellman** [comment]
Right now there isn't a good means of conveying that information.  I could add it as a deferred in the stream's metadata, I guess.  Thoughts?

**Comment by vspinu** [comment]
I would think that a natural place for those is as an argument to the `on-closed` callback, but that's not backward compatible, or is it?  If it's added as a metadata to the stream, it would be useful to have the stream itself as an argument to the callback.

**Comment by eslachance** [comment]
I would like to +1 this, as receiving the connection code can be important. I'm dealing with the Discord API which returns specific codes that define clearly why the socket was closed: 

![image](https://cloud.githubusercontent.com/assets/643344/22757246/18db8c4a-ee18-11e6-9671-42e2622287e8.png)

Knowing the reason for the disconnect in this case is critical to know what action should be taken. Perhaps an `:on-error` event?

**Comment by ubercow** [comment]
I think having it in the metadata or description of the stream would probably be best. Metadata being the change that'd require the fewest amount of changes to implement.

Aside from being a breaking change, adding an argument to on-closed would also require a bump of manifold too.

Gonna hack together a fork that uses metadata real quick and see how it looks/works.

**Comment by ubercow** [comment]
https://github.com/ztellman/aleph/compare/master...ubercow:websocket-close-metadata
In theory by the time on-closed is received you'd be able to access this metadata.
Hacked this together, but I really don't like it.

I was thinking of adding a new field to `netty/ChannelSink`, an `(atom {})` that'd be merged into the description. But I'd love to hear @ztellman's opinions before I go crazy changing core APIs.

The other thing on my mind is how we could support close codes for websocket servers too. But for that I don't think there's any way around changing manifold to add an argument to close. Perhaps that's best for another PR.
