### ISSUE TITLE
Add nanotime to ring-request map before queueing?

### ISSUE THREAD

**Issue by jeroenvandijk** [ztellman/aleph#273]
We want to take the time a request is waiting into account when processing a request. Would you be open for a patch to add `:request-time (System/nanoTime)`[here](https://github.com/ztellman/aleph/blob/9cdd682bd8e1827ae560139f1b21c61640f7d17c/src/aleph/http/core.clj#L180)?

Measuring on ring level would mean we miss the first part of queueing.

**Comment by ztellman** [comment]
The intended way to track this is via the executor stats, which do capture time spent on the queue, but this would be pretty harmless.  I'd prefer `:request-arrived` or something to that effect, though.
