### ISSUE TITLE
support for nested form-params in req options  

### ISSUE THREAD

**Issue by bhurlow** [ztellman/aleph#280]
e.g.

```clj
@(http/post "/foo/bar"
   { :form-params {:description "FIRSTNAME LASTNAME"}}))
```

https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/client.clj#L37-L45

**Comment by ztellman** [comment]
Interesting, I've tried to emulate all the relevant behaviors from clj-http, I'll look into why this isn't in there already.

**Comment by bhurlow** [comment]
suppose you could automatically coerce `:body` according to `content-type` header

**Comment by ztellman** [comment]
this should be addressed by https://github.com/ztellman/aleph/commit/3de504c187dc98a3f5b29485858faabf987477b3 and the other related commits

**Comment by bhurlow** [comment]
@ztellman thnx!
