### ISSUE TITLE
Refactoring of wrap-query-params changes nested parameter handling

### ISSUE THREAD

**Issue by camdez** [ztellman/aleph#284]
[The recent "refactoring" of `wrap-query-params`](https://github.com/ztellman/aleph/commit/d0b50d66c8f218f1f3451489f4ef2a6057f8b7f1#diff-0699d0c8d41a57446aff9b64094ddf35R393) introduces breaking changes to how nested query parameters are handled. I'm guessing this is not intentional based on the commit description (please close if I'm incorrect).

Behavior prior to d0b50d66c8f218f1f3451489f4ef2a6057f8b7f1:

```clj
(aleph.http.client-middleware/decorate-query-params
 {:query-params {:foo {:bar 42}}})
;; => {:query-string "foo%5Bbar%5D=42"}
```

Behavior after d0b50d66c8f218f1f3451489f4ef2a6057f8b7f1 (note function was renamed):

```clj
(aleph.http.client-middleware/wrap-query-params
 {:query-params {:foo {:bar 42}}})
;; => {:query-string "foo=%7B%3Abar+42%7D"}
```

The updated version also leaves the `nest-params` function unused, so it seems it may have been a simple oversight. 

/cc @solatis

**Comment by camdez** [comment]
FWIW:

```clj
(java.net.URLDecoder/decode "foo=%7B%3Abar+42%7D")
;; => "foo={:bar 42}"
(java.net.URLDecoder/decode "foo%5Bbar%5D=42")
;; => "foo[bar]=42"
```

**Comment by ztellman** [comment]
Okay, my bad for not vetting this change more carefully.  To be clear, the goal here is parity with whatever clj-http does, so if that has changed in more recent versions, breaking changes would be "correct".  I'm not sure if that's actually true here, though.

**Comment by camdez** [comment]
@ztellman Gotcha. I was just hoping to get clojure.spec running on my project; this required upgrading Aleph and then, to my surprise, my Stripe integration broke.  (Perhaps these param changes make sense as a separate release?)

I took a cursory glance at cli-http; the implementation of [`query-params-request`](https://github.com/dakrone/clj-http/blob/master/src/clj_http/client.clj#L750) does look similar to the refactored function here. (cli-http also has a [`wrap-nested-params`](https://github.com/dakrone/clj-http/blob/master/src/clj_http/client.clj#L945) middleware which appears relevant.)

**Comment by ztellman** [comment]
Well, breaking integrations is definitely not the desired outcome.  As I said, I didn't pay this a ton of attention at the time, I'll dig into the code and try understand the underlying intent.

**Comment by camdez** [comment]
@ztellman Much obliged. Please let me know if I can help.

**Comment by ztellman** [comment]
Well, maybe you can clarify what your expected behavior is. It appears that previously the behavior was to just url-encode the `pr-str` output of the value, which I can't imagine means much to the Stripe API.  The new behavior at least seems consistent with what I've seen elsewhere.

**Comment by camdez** [comment]
@ztellman Mea culpa. My "before" and "after" are backwards above. (I'll edit it after posting this.) The original (and desired) behavior is the `"foo[bar]=42"` version.

**Comment by ztellman** [comment]
Gotcha, that makes more sense :)

**Comment by camdez** [comment]
Corrected now!

**Comment by solatis** [comment]
I did not realize this was an issue, @camdez, and intended to make the behavior the same as clj-http. I'll take a look right away.

**Comment by solatis** [comment]
@ztellman @camdez is there perhaps an easy way we could provide backwards compatibility here ?

**Comment by solatis** [comment]
@camdez I ported the `wrap-nested-params` into aleph, could you take a look whether this properly addresses your issue ?

**Comment by camdez** [comment]
Hi, @solatis. The implementation on your branch is currently broken and failing tests:

```
Ran 29 tests containing 154 assertions.
0 failures, 136 errors.
Tests failed.
```

(The issue is the addition of `wrap-nested-params` to the `default-middleware`; the function is expecting a client as an argument whereas all of the other middleware expect a request map. But I'm honestly unsure what the purpose of `wrap-nested-params` is (`nest-params-request` seems to be the middleware).)

---

After looking at this a bit more, I see what cli-http was going for: the intent was to tease apart the handling of nested query parameters from the generation of the query string. These aspects do seem to be orthogonal, and decomplecting them will make it a lot nicer to use different schemes for nested parameter formatting. 

They *do* add `wrap-nested-params` to their `default-middleware` which, fortunately, means we should be able to do the same here and not break backwards-compatibility in the broadest case. Users explicitly providing a list of middleware will see changed handling of nested query parameters and will need to manually include the new middleware in their middleware stack.

---

Here are a couple tests that point to the changes in behavior. The first test would have passed before d0b50d66c8f218f1f3451489f4ef2a6057f8b7f1, but now fails:

```clj
(deftest test-nested-query-params
  (let [{:keys [query-string]} (-> {:query-params {:foo {:bar "baz"}}}
                                   middleware/wrap-query-params)]
    (is (= "foo[bar]=baz" (java.net.URLDecoder/decode query-string)))))

;; Fail in test-nested-query-params
;; expected: "foo[bar]=baz"
;;   actual: ("foo={:bar \"baz\"}")
```

The second *passes* on @solatis's branch:

```clj
(deftest test-nested-query-params2
  (let [nest-params-request #'middleware/nest-params-request
        {:keys [query-string]} (-> {:query-params {:foo {:bar "baz"}}}
                                   nest-params-request
                                   middleware/wrap-query-params)]
    (is (= "foo[bar]=baz" (java.net.URLDecoder/decode query-string)))))

;; 1 passed
```

**Comment by camdez** [comment]
Too much typing; decided to just fix it instead it. ;)
