### ISSUE TITLE
zlib compressed: a solution

### ISSUE THREAD

**Issue by eslachance** [ztellman/aleph#289]
Hi there! I'm not sure just how much "magic handling" you want to do in aleph. The API I'm using sends zlib compressed packets in the websocket and it took me a bit of time to figure out how to handle them. Here is what solution I came up with, if ever you'd want to add that in the lib - or somewhere in a readme perhaps?

With some help from @vgeshel we found this little piece of code that does the decompression using `java.util.zip.Inflater`: https://github.com/amatus/GNUnet-in-Clojure/blob/master/src/main/clojure/org/gnu/clojure/gnunet/zip.clj 

Then it's a simple matter of doing `(String. (byte-array (z/inflate msg)))` where `msg` is the incoming packet, to get it. In context of the function that handles all my incoming packets: 

```clj
; with (:require [project.zip :as z])

(defn on-message [msg]
  (let [st (if (instance? String msg) 
             msg
             (String. (byte-array (z/inflate msg))))
        m (json/parse-string st true)]
    ; Do stuff with message
    ))
```

**Comment by ztellman** [comment]
My preference here would be to use the [byte-transforms](https://github.com/ztellman/byte-transforms) library, in which case you could just do `(-> msg (bt/decompress :gzip) bs/to-string)`.  I don't see any real value in baking this into Aleph, since it's not part of the core protocol.  Does this not work for you?

**Comment by eslachance** [comment]
I guess either solution would work - perhaps mine is more targeted towards this exact situation whereas byte-transforms is a broader approach. To be honest having this ticket available here might help other users in the future if they have the same requirements :) Thanks!
