### ISSUE TITLE
Nested query param behavior changed when content type specified

### ISSUE THREAD

**Issue by camdez** [ztellman/aleph#294]
This is a follow-up to #284 (and the related work in #286).

While that work was sufficient to restore the pre-refactoring handling of nested parameters, that had an undiscovered caveat: it only worked when a content type was not specified.

So this test passes...

```clj
(deftest test-nested-query-params
  (let [req {:query-params {:foo {:bar "baz"}}}
        {:keys [query-string]} (reduce #(%2 %1) req middleware/default-middleware)]
    (is (= "foo[bar]=baz" (URLDecoder/decode query-string)))))
```

But this one fails:

```clj
(deftest test-nested-query-params-with-content-type
  (let [req {:query-params {:foo {:bar "baz"}}
             :content-type :json}
        {:keys [query-string]} (reduce #(%2 %1) req middleware/default-middleware)]
    (is (= "foo[bar]=baz" (URLDecoder/decode query-string)))))

;; FAIL in (test-nested-query-params-with-content-type) (client_middleware_test.clj:33)
;; expected: "foo[bar]=baz"
;;   actual: "foo={:bar \"baz\"}"
;;     diff: - "foo[bar]=baz"
;;           + "foo={:bar \"baz\"}"
```

🤔 

The culprit is [this conditional](https://github.com/ztellman/aleph/blob/6e1542d1d751a59d8b50a784fa4ef771a64192df/src/aleph/http/client_middleware.clj#L188-L189). This doesn't really seem like necessary behavior—but I'd welcome help in thinking through the various cases and what I might be missing—and it is certainly a change from how things worked before the refactoring.

**Comment by ztellman** [comment]
Hmmm.  I don't see an obvious relationship between form-urlencoded bodies and nested query params, but I'll need to look at the RFCs to make sure it's not some weird quirk of the extended HTTP spec.  If anyone already knows one way or another, I'd be happy to hear from them.

**Comment by kachayev** [comment]
@camdez @ztellman This behavior was ported from `clj_http` that has the same issue (introduced after request body coercion was added).

https://github.com/dakrone/clj-http/issues/427

**Comment by kachayev** [comment]
Following up. The issue mentioned above on the `clj-http` side was closed by adding new params on how to control nested params behavior. I'm going to port the solution to `aleph` as well. Will update my PR on [:multi-param-style](https://github.com/ztellman/aleph/pull/353), otherwise it would introduce a lot of conflicts.
