### ISSUE TITLE
Will Aleph support permessage-deflate for WebSocket ?

### ISSUE THREAD

**Issue by muyinliu** [ztellman/aleph#304]
See: [Compression Extensions for WebSocket draft-ietf-hybi-permessage-compression-28](https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-28)

**Comment by ztellman** [comment]
When talking about protocol-level support, generally Aleph will support whatever Netty does.  Based on a quick look, it appears this is supported (https://netty.io/4.1/api/io/netty/handler/codec/http/websocketx/extensions/package-summary.html), but I'll need to spend some time hooking it up.  I'll leave this issue open until that's complete.

**Comment by muyinliu** [comment]
Thank you.

**Comment by kachayev** [comment]
@ztellman I think it's safe now to close this issue 🤔
