### ISSUE TITLE
HTTP client: closing stream seems to have no effect

### ISSUE THREAD

**Issue by a1exsh** [ztellman/aleph#306]
I've got a `byte_streams.InputStream` as a result of call to `aleph.http/request` with `:as :stream` option.

Now if I try to close it by calling `(.close s)`, nothing seems to happen.  The stream can still be used to read more data from it and, more importantly, the server never notices that the client tries to close the stream.

What is supported way to close the client input stream?

**Comment by PetrGlad** [comment]
As an option we could switch to apache/httpcomponents-based library for http calls which gives more control over connection options. (Need to figure out how to configure buffering options though).

**Comment by ztellman** [comment]
Closing the stream will only have an effect if the body hasn't already been entirely transmitted. How large is the body, and how slowly is it being sent?

**Comment by a1exsh** [comment]
@ztellman in our case body is an actual contiguous stream of data from the server, which is normally never closed (unless the server dies or needs to rebalance clients, etc.)

It can be slow or fast, but we know we get more data from the server at least every 30 seconds.

Could you point me to the actual code that is invoked when `close` is being called on `byte_streams.InputStream` in this case?  I could not find the implementation...

**Comment by ztellman** [comment]
Apologies, I only just saw your response.  The code being executed is here: https://github.com/ztellman/byte-streams/blob/master/src/byte_streams/pushback_stream.clj#L241.  This will cause the next `put` call to return `false` (https://github.com/ztellman/byte-streams/blob/master/src/byte_streams/pushback_stream.clj#L131), which should cause the connection to close.

However, this will only happen when new data arrives, it will not immediately close the upstream connection when `close` is called.  This is probably what you're seeing here.  Is this causing issues on your end, or is it just confusing?

**Comment by a1exsh** [comment]
@ztellman thanks for the explanation.  In our case the effect is that we might not be able to re-open consumer stream promptly, because the server still believes that the old connection is used.  The server has a timeout, so eventually the client succeeds in opening the stream again.  So this is not a blocker, merely an inconvenience.

We've hit a bigger issue however, which I'll try to describe separately.
