### ISSUE TITLE
Trying to require aleph breaks the world

### ISSUE THREAD

**Issue by prismofeverything** [ztellman/aleph#307]
Currently having an issue just trying to require aleph as a dependency.

In my `project.clj`:

    [aleph "0.4.3"]

Just having aleph as a dependency in `project.clj` shows this error on startup:

    #error {
     :cause vector does not exist
     :via
     [{:type clojure.lang.Compiler$CompilerException
       :message java.lang.IllegalAccessError: vector does not exist, compiling:(byte_streams/graph.clj:1:1)
       :at [clojure.lang.Compiler load Compiler.java 7391]}
      {:type java.lang.IllegalAccessError
       :message vector does not exist
       :at [clojure.core$refer invokeStatic core.clj 4119]}]
     :trace
     [[clojure.core$refer invokeStatic core.clj 4119]
      [clojure.core$refer doInvoke core.clj 4087]
      [clojure.lang.RestFn applyTo RestFn.java 139]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_lib invokeStatic core.clj 5755]
      [clojure.core$load_lib doInvoke core.clj 5717]
      [clojure.lang.RestFn applyTo RestFn.java 142]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_libs invokeStatic core.clj 5774]
      [clojure.core$load_libs doInvoke core.clj 5758]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$require invokeStatic core.clj 5796]
      [clojure.core$require doInvoke core.clj 5796]
      [clojure.lang.RestFn invoke RestFn.java 436]
      [byte_streams.graph$eval2770$loading__5569__auto____2771 invoke graph.clj 1]
      [byte_streams.graph$eval2770 invokeStatic graph.clj 1]
      [byte_streams.graph$eval2770 invoke graph.clj 1]
      [clojure.lang.Compiler eval Compiler.java 6927]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler load Compiler.java 7379]
      [clojure.lang.RT loadResourceScript RT.java 372]
      [clojure.lang.RT loadResourceScript RT.java 363]
      [clojure.lang.RT load RT.java 453]
      [clojure.lang.RT load RT.java 419]
      [clojure.core$load$fn__5677 invoke core.clj 5893]
      [clojure.core$load invokeStatic core.clj 5892]
      [clojure.core$load doInvoke core.clj 5876]
      [clojure.lang.RestFn invoke RestFn.java 408]
      [clojure.core$load_one invokeStatic core.clj 5697]
      [clojure.core$load_one invoke core.clj 5692]
      [clojure.core$load_lib$fn__5626 invoke core.clj 5737]
      [clojure.core$load_lib invokeStatic core.clj 5736]
      [clojure.core$load_lib doInvoke core.clj 5717]
      [clojure.lang.RestFn applyTo RestFn.java 142]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_libs invokeStatic core.clj 5778]
      [clojure.core$load_libs doInvoke core.clj 5758]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$require invokeStatic core.clj 5796]
      [clojure.core$require doInvoke core.clj 5796]
      [clojure.lang.RestFn invoke RestFn.java 457]
      [byte_streams$eval2764$loading__5569__auto____2765 invoke byte_streams.clj 1]
      [byte_streams$eval2764 invokeStatic byte_streams.clj 1]
      [byte_streams$eval2764 invoke byte_streams.clj 1]
      [clojure.lang.Compiler eval Compiler.java 6927]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler load Compiler.java 7379]
      [clojure.lang.RT loadResourceScript RT.java 372]
      [clojure.lang.RT loadResourceScript RT.java 363]
      [clojure.lang.RT load RT.java 453]
      [clojure.lang.RT load RT.java 419]
      [clojure.core$load$fn__5677 invoke core.clj 5893]
      [clojure.core$load invokeStatic core.clj 5892]
      [clojure.core$load doInvoke core.clj 5876]
      [clojure.lang.RestFn invoke RestFn.java 408]
      [clojure.core$load_one invokeStatic core.clj 5697]
      [clojure.core$load_one invoke core.clj 5692]
      [clojure.core$load_lib$fn__5626 invoke core.clj 5737]
      [clojure.core$load_lib invokeStatic core.clj 5736]
      [clojure.core$load_lib doInvoke core.clj 5717]
      [clojure.lang.RestFn applyTo RestFn.java 142]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_libs invokeStatic core.clj 5774]
      [clojure.core$load_libs doInvoke core.clj 5758]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$require invokeStatic core.clj 5796]
      [clojure.core$require doInvoke core.clj 5796]
      [clojure.lang.RestFn invoke RestFn.java 619]
      [aleph.netty$eval2758$loading__5569__auto____2759 invoke netty.clj 1]
      [aleph.netty$eval2758 invokeStatic netty.clj 1]
      [aleph.netty$eval2758 invoke netty.clj 1]
      [clojure.lang.Compiler eval Compiler.java 6927]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler load Compiler.java 7379]
      [clojure.lang.RT loadResourceScript RT.java 372]
      [clojure.lang.RT loadResourceScript RT.java 363]
      [clojure.lang.RT load RT.java 453]
      [clojure.lang.RT load RT.java 419]
      [clojure.core$load$fn__5677 invoke core.clj 5893]
      [clojure.core$load invokeStatic core.clj 5892]
      [clojure.core$load doInvoke core.clj 5876]
      [clojure.lang.RestFn invoke RestFn.java 408]
      [clojure.core$load_one invokeStatic core.clj 5697]
      [clojure.core$load_one invoke core.clj 5692]
      [clojure.core$load_lib$fn__5626 invoke core.clj 5737]
      [clojure.core$load_lib invokeStatic core.clj 5736]
      [clojure.core$load_lib doInvoke core.clj 5717]
      [clojure.lang.RestFn applyTo RestFn.java 142]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_libs invokeStatic core.clj 5774]
      [clojure.core$load_libs doInvoke core.clj 5758]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$require invokeStatic core.clj 5796]
      [clojure.core$require doInvoke core.clj 5796]
      [clojure.lang.RestFn invoke RestFn.java 619]
      [aleph.http.core$eval2752$loading__5569__auto____2753 invoke core.clj 1]
      [aleph.http.core$eval2752 invokeStatic core.clj 1]
      [aleph.http.core$eval2752 invoke core.clj 1]
      [clojure.lang.Compiler eval Compiler.java 6927]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler load Compiler.java 7379]
      [clojure.lang.RT loadResourceScript RT.java 372]
      [clojure.lang.RT loadResourceScript RT.java 363]
      [clojure.lang.RT load RT.java 453]
      [clojure.lang.RT load RT.java 419]
      [clojure.core$load$fn__5677 invoke core.clj 5893]
      [clojure.core$load invokeStatic core.clj 5892]
      [clojure.core$load doInvoke core.clj 5876]
      [clojure.lang.RestFn invoke RestFn.java 408]
      [clojure.core$load_one invokeStatic core.clj 5697]
      [clojure.core$load_one invoke core.clj 5692]
      [clojure.core$load_lib$fn__5626 invoke core.clj 5737]
      [clojure.core$load_lib invokeStatic core.clj 5736]
      [clojure.core$load_lib doInvoke core.clj 5717]
      [clojure.lang.RestFn applyTo RestFn.java 142]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_libs invokeStatic core.clj 5774]
      [clojure.core$load_libs doInvoke core.clj 5758]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$require invokeStatic core.clj 5796]
      [clojure.core$require doInvoke core.clj 5796]
      [clojure.lang.RestFn invoke RestFn.java 551]
      [aleph.http.server$eval2746$loading__5569__auto____2747 invoke server.clj 1]
      [aleph.http.server$eval2746 invokeStatic server.clj 1]
      [aleph.http.server$eval2746 invoke server.clj 1]
      [clojure.lang.Compiler eval Compiler.java 6927]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler load Compiler.java 7379]
      [clojure.lang.RT loadResourceScript RT.java 372]
      [clojure.lang.RT loadResourceScript RT.java 363]
      [clojure.lang.RT load RT.java 453]
      [clojure.lang.RT load RT.java 419]
      [clojure.core$load$fn__5677 invoke core.clj 5893]
      [clojure.core$load invokeStatic core.clj 5892]
      [clojure.core$load doInvoke core.clj 5876]
      [clojure.lang.RestFn invoke RestFn.java 408]
      [clojure.core$load_one invokeStatic core.clj 5697]
      [clojure.core$load_one invoke core.clj 5692]
      [clojure.core$load_lib$fn__5626 invoke core.clj 5737]
      [clojure.core$load_lib invokeStatic core.clj 5736]
      [clojure.core$load_lib doInvoke core.clj 5717]
      [clojure.lang.RestFn applyTo RestFn.java 142]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_libs invokeStatic core.clj 5778]
      [clojure.core$load_libs doInvoke core.clj 5758]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$require invokeStatic core.clj 5796]
      [clojure.core$require doInvoke core.clj 5796]
      [clojure.lang.RestFn invoke RestFn.java 482]
      [aleph.http$eval2697$loading__5569__auto____2698 invoke http.clj 1]
      [aleph.http$eval2697 invokeStatic http.clj 1]
      [aleph.http$eval2697 invoke http.clj 1]
      [clojure.lang.Compiler eval Compiler.java 6927]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler load Compiler.java 7379]
      [clojure.lang.RT loadResourceScript RT.java 372]
      [clojure.lang.RT loadResourceScript RT.java 363]
      [clojure.lang.RT load RT.java 453]
      [clojure.lang.RT load RT.java 419]
      [clojure.core$load$fn__5677 invoke core.clj 5893]
      [clojure.core$load invokeStatic core.clj 5892]
      [clojure.core$load doInvoke core.clj 5876]
      [clojure.lang.RestFn invoke RestFn.java 408]
      [clojure.core$load_one invokeStatic core.clj 5697]
      [clojure.core$load_one invoke core.clj 5692]
      [clojure.core$load_lib$fn__5626 invoke core.clj 5737]
      [clojure.core$load_lib invokeStatic core.clj 5736]
      [clojure.core$load_lib doInvoke core.clj 5717]
      [clojure.lang.RestFn applyTo RestFn.java 142]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_libs invokeStatic core.clj 5774]
      [clojure.core$load_libs doInvoke core.clj 5758]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$require invokeStatic core.clj 5796]
      [clojure.core$require doInvoke core.clj 5796]
      [clojure.lang.RestFn invoke RestFn.java 482]
      [ophion.core$eval14$loading__5569__auto____15 invoke core.clj 1]
      [ophion.core$eval14 invokeStatic core.clj 1]
      [ophion.core$eval14 invoke core.clj 1]
      [clojure.lang.Compiler eval Compiler.java 6927]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler load Compiler.java 7379]
      [clojure.lang.RT loadResourceScript RT.java 372]
      [clojure.lang.RT loadResourceScript RT.java 363]
      [clojure.lang.RT load RT.java 453]
      [clojure.lang.RT load RT.java 419]
      [clojure.core$load$fn__5677 invoke core.clj 5893]
      [clojure.core$load invokeStatic core.clj 5892]
      [clojure.core$load doInvoke core.clj 5876]
      [clojure.lang.RestFn invoke RestFn.java 408]
      [clojure.core$load_one invokeStatic core.clj 5697]
      [clojure.core$load_one invoke core.clj 5692]
      [clojure.core$load_lib$fn__5626 invoke core.clj 5737]
      [clojure.core$load_lib invokeStatic core.clj 5736]
      [clojure.core$load_lib doInvoke core.clj 5717]
      [clojure.lang.RestFn applyTo RestFn.java 142]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$load_libs invokeStatic core.clj 5774]
      [clojure.core$load_libs doInvoke core.clj 5758]
      [clojure.lang.RestFn applyTo RestFn.java 137]
      [clojure.core$apply invokeStatic core.clj 648]
      [clojure.core$require invokeStatic core.clj 5796]
      [clojure.core$require doInvoke core.clj 5796]
      [clojure.lang.RestFn invoke RestFn.java 408]
      [user$eval5 invokeStatic form-init4191007883785554500.clj 1]
      [user$eval5 invoke form-init4191007883785554500.clj 1]
      [clojure.lang.Compiler eval Compiler.java 6927]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler eval Compiler.java 6916]
      [clojure.lang.Compiler load Compiler.java 7379]
      [clojure.lang.Compiler loadFile Compiler.java 7317]
      [clojure.main$load_script invokeStatic main.clj 275]
      [clojure.main$init_opt invokeStatic main.clj 277]
      [clojure.main$init_opt invoke main.clj 277]
      [clojure.main$initialize invokeStatic main.clj 308]
      [clojure.main$null_opt invokeStatic main.clj 342]
      [clojure.main$null_opt invoke main.clj 339]
      [clojure.main$main invokeStatic main.clj 421]
      [clojure.main$main doInvoke main.clj 384]
      [clojure.lang.RestFn invoke RestFn.java 421]
      [clojure.lang.Var invoke Var.java 383]
      [clojure.lang.AFn applyToHelper AFn.java 156]
      [clojure.lang.Var applyTo Var.java 700]
      [clojure.main main main.java 37]]}

I looked in the output of `mvn dependency:tree` and it looks like `clj-tuple` is in there:

    [INFO] +- aleph:aleph:jar:0.4.3:compile
    [INFO] |  +- org.clojure:tools.logging:jar:0.3.1:compile
    [INFO] |  +- io.netty:netty-all:jar:4.1.9.Final:compile
    [INFO] |  +- manifold:manifold:jar:0.1.6:compile
    [INFO] |  |  +- io.aleph:dirigiste:jar:0.1.5:compile
    [INFO] |  |  \- riddley:riddley:jar:0.1.14:compile
    [INFO] |  +- byte-streams:byte-streams:jar:0.2.2:compile
    [INFO] |  |  +- primitive-math:primitive-math:jar:0.1.5:compile
    [INFO] |  |  \- clj-tuple:clj-tuple:jar:0.2.2:compile
    [INFO] |  \- potemkin:potemkin:jar:0.4.3:compile

Any idea what is going on? Thanks!

**Comment by ztellman** [comment]
Can you give me the full output of `lein deps :tree`?

**Comment by prismofeverything** [comment]
[aleph "0.4.3"]
       [byte-streams "0.2.2"]
         [clj-tuple "0.2.2"]
         [primitive-math "0.1.5"]
       [io.netty/netty-all "4.1.9.Final"]
       [manifold "0.1.6"]
         [io.aleph/dirigiste "0.1.5"]
         [riddley "0.1.14"]
       [org.clojure/tools.logging "0.3.1" :exclusions [[org.clojure/clojure]]]
       [potemkin "0.4.3"]
     [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
     [com.taoensso/timbre "4.8.0"]
       [com.taoensso/encore "2.88.0"]
         [com.taoensso/truss "1.3.6"]
         [org.clojure/tools.reader "0.10.0"]
       [io.aviso/pretty "0.1.33"]
     [org.apache.tinkerpop/tinkergraph-gremlin "3.2.3"]
       [org.apache.commons/commons-lang3 "3.3.1"]
       [org.apache.tinkerpop/gremlin-core "3.2.3"]
         [com.carrotsearch/hppc "0.7.1"]
         [com.jcabi/jcabi-manifests "1.1" :exclusions [[org.slf4j/slf4j-api]]]
           [com.jcabi/jcabi-log "0.14"]
         [commons-configuration "1.10" :exclusions [[commons-logging]]]
           [commons-lang "2.6"]
         [org.apache.tinkerpop/gremlin-shaded "3.2.3"]
         [org.javatuples/javatuples "1.2"]
         [org.slf4j/jcl-over-slf4j "1.7.21"]
         [org.slf4j/slf4j-api "1.7.21"]
         [org.yaml/snakeyaml "1.15"]
     [org.clojure/clojure "1.8.0"]
     [org.clojure/data.json "0.2.6"]
     [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]

**Comment by ztellman** [comment]
So the implication of that error is that you're using an ancient version of `clj-tuple` (see this old issue for an example https://github.com/ztellman/automat/issues/19), but that's not what your dependencies say.  I'm kind of at a loss, can you try wiping `~/.m2/repository/` and seeing if that changes anything?

**Comment by ztellman** [comment]
This also could be explained by an AOT dependency that contains an older version of clj-tuple, if by any chance you've got an internal dependency you aren't showing here.

**Comment by prismofeverything** [comment]
Ah yep, you are correct. Dumb ancient plugin in lein profiles AOT compiled. Thanks for the lead there. Gah!
