### ISSUE TITLE
Detecting half-open connections

### ISSUE THREAD

**Issue by AlexHill** [ztellman/aleph#311]
Firstly thanks for Aleph.

I'm using Aleph's websocket client and I'm having trouble detecting when network interruptions occur between client and server. My understanding of how TCP works is that there's no particular way to detect when a peer disappears except to write to the socket. However, Aleph seems happy to write to a websocket for a very long time, even when the network connection to the peer has been severed.

After about 20 minutes of consistently sending data, I get a `java.io.IOException` as below.

If this is normal, I guess I can implement a keepalive and read timeout in my application code. But is there any way of doing this at the Aleph/Netty layer so I can keep my application code a bit cleaner?

```
java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by AlexHill** [comment]
I'm still curious to hear your thoughts on this but I've solved the problem in the interim by adding a Netty `IdleStateHandler` to the channel's pipeline, pinging after the connecting is idle for a certain period and closing the connection if it doesn't receive a response.

Would you be interested in a PR adding this functionality to aleph?

**Comment by ztellman** [comment]
That's not really a universal need or desire in all websocket use cases.  Detecting when the connection is closed depends on the underlying TCP stack, so I can't speak as to why it takes 20 minutes for that to occur, but there may be some parameters you can tweak.  

I would be willing to consider some sort of mechanism built on top of websocket's ping/pong frames to detect timeouts, but I'll need to do some research on how these are used in other frameworks.

**Comment by AlexHill** [comment]
Thanks, I think I've got my head around it a bit more. Perhaps the time before receiving an error from the TCP stack depends on how much data is being pushed without acknowledgement? Anyway, the point is I get now that that is out of my control.

I would love to see optional keepalives/timeouts based on Ping/Pong frames built in to Aleph. The websocket spec says Pong frames must be sent in response to Ping frames with the same payload, so a timeout based on Ping/Pong should work with any compliant websocket implementation. For the record, this is basically what I've done:

```clojure
(defn- enable-ping-timeout
  "Adds a handler to the Netty channel's pipeline to send pings after
  interval seconds with nothing sent, and close the connection if after
  timeout seconds nothing is received. If timeout is omitted, two times
  the interval value will be used."
  ([ws interval]
   (enable-ping-timeout ws interval (* 2 interval)))
  ([ws interval timeout]
   (let [ping-handler
         (proxy [ChannelDuplexHandler] []
           ;; The method that handles the IdleStateHandler's event. If we
           ;; haven't sent anything in a while, send a ping. If we haven't
           ;; received anything back in a while, raise an exception and let
           ;; aleph handle closing the connection.
           (userEventTriggered [ctx evt]
             (when (instance? IdleStateEvent evt)
               (condp = (.state evt)
                 IdleState/READER_IDLE
                 (throw (Exception. "Nothing received from server"))
                 IdleState/WRITER_IDLE
                 (.writeAndFlush ctx (PingWebSocketFrame.))))))

     ;; Add our handler to the pipeline
     (-> (.pipeline (:aleph/channel (meta ws)))
         (.addBefore "handler" "idleHandler" (IdleStateHandler. timeout interval 0))
         (.addAfter "idleHandler" "pingHandler" ping-handler)))))
```
