### ISSUE TITLE
Pool lock held by thread with state TERMINATED 

### ISSUE THREAD

**Issue by blandinw** [ztellman/aleph#313]
We use `aleph (0.4.4-alpha2)` for the HTTP client (and server, but it's probably irrelevant here) with default pool and executor as well as `byte-stream (0.2.2)` to convert bodies to `byte[]` or `String`.
We perform ~3 requests per second per process using this client and are seeing what seems to be a deadlock ~1-2 times a day.

After digging deeper, the `dirigiste.Pool` lock seems to be held by a thread from the `manifold-wait-*` pool in state `TERMINATED` (!). The wait-pool was probably used to execute the `aleph.http/request` deferred chain at some point while consuming the body (see `wait-for` calls in `manifold.stream.*`). I have yet to find a possible interlacing that could cause this, and upon inspection of the Pool locking code, I don't know where a thread could possibly terminate while holding the lock (although it would be safer to wrap code in a try/finally every time we lock as per https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantLock.html).
I'm still digging but I thought I'd open the issue to see if you had ideas as to what could be wrong or how to debug that more efficiently.

REPL session in stuck process:
```
aleph.http=>   (let [lock (get-field io.aleph.dirigiste.Pool "_lock" default-connection-pool)
        #_=>         owner-thread (get-method java.util.concurrent.locks.ReentrantLock
        #_=>                                  "getOwner"
        #_=>                                  (make-array Class 0)
        #_=>                                  lock
        #_=>                                  (make-array Object 0))]
        #_=>     [(.getName owner-thread) (.getState owner-thread)])
["manifold-wait-1316" #object[java.lang.Thread$State 0x10b2e813 "TERMINATED"]]
```

Thread dump: https://gist.github.com/blandinw/11947f6587cd672c53794efd7fe10c0c

**Comment by ztellman** [comment]
Hmm, that's concerning, I'll take a look.

**Comment by ztellman** [comment]
So I've looked at the code, and I'm not sure how this could happen.  The reason I don't use the try/finally idiom is so I can avoid holding onto a lock while calling into a user-provided callback (see https://github.com/ztellman/dirigiste/blob/master/src/io/aleph/dirigiste/Pool.java#L106-L107).  Are you calling `Thread.interrupt()` or anything like that in your application code?

**Comment by blandinw** [comment]
Thank you for looking into it!
We don't mess with threads lifecycle in our application code as far as I can tell.
Regarding the try/finally idiom, I wonder if there's a way to structure the code such that each lock has a corresponding finally unlock.

I plan to carve out some time to get a minimal repro (many threads banging on the lock using the http client + byte-stream). I'm also hoping to catch the offending thread's stacktrace using YourKit's thread telemetry. Let me know if you can think of a better way.

**Comment by ztellman** [comment]
The only thing I can think of is that I was trying to be a bit clever with the stack size for the threads in the wait-pool, and maybe the stack is getting blown in the middle of the pool-handling code.  I've just cut `0.1.7-alpha1`, which doesn't try to do anything clever, and may totally fix your problem.  I think that's worth testing before trying anything else.

**Comment by blandinw** [comment]
Sounds good, I'm upgrading to manifold 0.1.7-alpha1 and we'll see!

**Comment by ztellman** [comment]
Has the problem resurfaced?

**Comment by blandinw** [comment]
The problem has not resurfaced since we moved to the new version!
I'll reopen the issue if it happens again.
Thank you for your great support! 🎉
