### ISSUE TITLE
Talking to SNI-enabled hosts

### ISSUE THREAD

**Issue by maxcountryman** [ztellman/aleph#317]
Say I want to talk to a host that's using SNI to serve up secured responses. One example might be an application hosted on Heroku. For the SSL handshake to work properly, I should provide the "servername", let's say "example.com", but the host I talk to might have a CNAME like "example.com.herokudns.com"--the implication is I'll want to provide my own `SslContext` object with respect to the `ChannelPipeline` instance.

It seems that I can work around this with a connection pool that uses a pipeline transform. For example:

```clojure
(def connection-pool
  (http/connection-pool
    {:connection-options
     {:pipeline-transform
      (fn [p]
        (let [insecure-ssl-context (netty/insecure-ssl-client-context)
              ssl-handler (.newHandler insecure-ssl-context (-> p .channel .alloc) "example.com" 443)]
          (.replace p "ssl-handler" "ssl-handler" ssl-handler)))
      :keep-alive? true}}))
```

But this is a hack: I've had to hardcode the name of the preexisting SSL handler in order to replace it with my own. It seems like being able to provide my own `SslContext` instance via the `:connection-options` map would be the way to go, but there I don't think I have access to the `ChannelPipeline` instance which seems needed. Furthermore I need a connection pool per host I intend to treat this way--that might not be the worst thing in the world, but worth mentioning.

Is there a better way of doing this kind of thing?

**Comment by kachayev** [comment]
@maxcountryman Yep, there's a better way: you don't need to hardcode the name of the preexisting SSL handler, you could you [this](https://netty.io/4.1/api/io/netty/channel/ChannelPipeline.html#replace-java.lang.Class-java.lang.String-io.netty.channel.ChannelHandler-) method to replace the handler by the type instead of the name. So, something like

```(.replace p (class ssl-handler) "ssl-handler" ssl-handler)```

should work.

**Comment by kachayev** [comment]
I'm closing this in favor of https://github.com/ztellman/aleph/issues/445.
