### ISSUE TITLE
:raw-stream produces byte[] instead of stream

### ISSUE THREAD

**Issue by fmnoise** [ztellman/aleph#328]
The following example from http://aleph.io/aleph/literate.html#aleph.examples.http
```clojure
@(d/chain   
  (http/get 
   "https://gist.githubusercontent.com/fmnoise/3441ca4c95c1d3244568a49760917880/raw/e2da0510fa74416d43db054d0ff7fce986174f56/test.csv" 
   {:raw-stream? true})   
  :body   
  #(s/map bs/to-byte-array %)   
  #(s/reduce conj [] %)   
  bs/to-string)
```
fails with  ```java.lang.IllegalArgumentException: cannot convert byte[] to source```

env: 
aleph 0.4.3
clojure 1.8.0
java 1.8.0_131

**Comment by ztellman** [comment]
Hi, thanks for reporting this.  The example there is incorrect w.r.t. the proper way to accomplish this, you need to specify `raw-stream?` on the connection pool, not the request.  I will update the example to reflect this.
