### ISSUE TITLE
Switch from netty-all to specifying Netty JARs?

### ISSUE THREAD

**Issue by danielcompton** [ztellman/aleph#335]
I spent a bit of time tracking down a nasty coredumping issue which turned out to be caused because Aleph bundles netty-all, and the Google Cloud SDK depends on individual netty JARs.

As best as I can tell (https://github.com/netty/netty/issues/4671, [CASSANDRA-10984](https://issues.apache.org/jira/browse/CASSANDRA-10984)), netty-all is a kind of uberjar of all Netty classes, designed for people that just want to download a JAR and get running with Netty. If you're using Maven it is instead recommended to depend on specific Netty dependencies.

Now that I've figured out the problem I can just exclude the netty-all JAR to get the behaviour I want, but I thought it might save other people some anguish if Aleph moved to depending on explicit Netty JARs.

What are your thoughts on this? It looks like [eventually](https://github.com/netty/netty/issues/4671#issuecomment-257031451) netty-all may just become a dependency container for all of the other Netty JARs, in which case there would be no issue, however that seems like it may be a way off.

**Comment by ztellman** [comment]
I don't have a strong opinion on this.  Back when I was first targeting Netty 4, I tried to enumerate packages Aleph depended on, couldn't get it to work in a reasonable amount of time, and so just targeted the uberjar.  If someone were to make it work for me, I'd have no problem merging the PR, but I don't see this as an immediate issue that requires fixing.

**Comment by danielcompton** [comment]
I've made a PR for this, but I agree it's not an urgent issue. I've done some testing on an actual project and everything seems fine.
