### ISSUE TITLE
Transforming websocket messages

### ISSUE THREAD

**Issue by AlexHill** [ztellman/aleph#338]
Hi,

A very useful feature in chord (built on http-kit) is the concept of a websocket formatter. The duplex channel you get from its `with-channel` macro  (analogous to `aleph.http/websocket-connection`) can optionally have serialisation and deserialisation functions applied to it, so you put and take Clojure data structures but over the wire it's EDN, transit, JSON, etc.

Is this something you could see integrated into Aleph? If not, does the following seem like a reasonable way to handle this in user code?

```
(defn format-stream
  "Take a manifold spliced stream, a freeze and a thaw function, and return
  a new spliced stream which applies the freeze and thaw functions to puts
  and takes respectively."
  [s freeze thaw]
  (let [sink (stream/map freeze (stream/stream))]
    (stream/connect sink s)
    (stream/splice sink (stream/map thaw s))))
```

Thanks,
Alex

**Comment by AlexHill** [comment]
If the part of the Netty pipeline that performed the final `netty/put!` were separated in to a separate handler, it would be possible to inject a handler that performed arbitrary conversion to/from text or bytes into the pipeline. Does that sound feasible?

**Comment by ztellman** [comment]
Hi, sorry for not responding to this sooner.  Yes, the `format-stream` you define is the preferred way to handle this, and is something I think is best left in the application code.

**Comment by jdf-id-au** [comment]
For anyone using this issue as "documentation" for how to format a stream, do it like this instead (as seen at [crossclj](https://crossclj.info/fun/manifold.stream/splice.html)):
```
(defn format-stream [s freeze thaw]
  (let [out (s/stream)]
    (s/connect (s/map freeze out) s)
    (s/splice out (s/map thaw s))))
```
...otherwise you get `cannot convert manifold.stream.SourceProxy to sink`.
