### ISSUE TITLE
Aleph 0.4.5-alpha1 doesn't work with Java 7

### ISSUE THREAD

**Issue by camsaul** [ztellman/aleph#344]
It fails with this error 

```
java.lang.UnsupportedClassVersionError: aleph/utils/PoolTimeoutException : Unsupported major.minor version 52.
```

when launching. 0.4.4 worked without issue. From what I understand this means you compiled with Java 8. If you set `:javac-options ["-target" "1.7", "-source" "1.7"]` in `profiles.clj` it should compile for a Java 7 target

**Comment by camsaul** [comment]
@ztellman sorry to be super obnoxious, but is there any chance you could push an alpha2 with the Java 7 fix? I can't solve our Java 9 woes without the stuff from alpha1 that stops using `javax.xml.bind` classes. But we still want to support Java 7 as well

**Comment by ztellman** [comment]
Sorry for not updating the issue, but I actually already pushed alpha2.  It should be available now.

**Comment by camsaul** [comment]
thanks a ton!
