### ISSUE TITLE
Decoding error

### ISSUE THREAD

**Issue by ivarref** [ztellman/aleph#348]
Hi, and thanks for a good library!

I've encountered a strange decoding error when using curl .

To reproduce start an aleph server:
```clojure
(ns aleph-encoding-bug.core
  (:require [byte-streams :as bs]
            [aleph.http :as http]))

(defn handler [req]
  (let [body-string (bs/to-string (:body req))]
    (if-let [bug (second (re-matches #".*(sentralbyr[^å]).*" body-string))]
      (do (println "encoding error =>" bug)
          {:status  500
           :headers {"content-type" "text/plain"}
           :body    "encoding bug"})
      (do (println "everything seems fine")
          {:status  200
           :headers {"content-type" "text/plain"}
           :body    "OK"}))))

(defonce server (http/start-server (fn [req] (handler req)) {:port 8080 :raw-stream? true}))
```

And in a terminal do:

```bash
$ curl https://raw.githubusercontent.com/ivarref/aleph-encoding-problem/master/bad.json -o bad.json
$ curl -d @bad.json http://localhost:8080/
encoding bug
```

```bash
$ curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

Any ideas on what might be causing this?
Full project reproducing issue is available at https://github.com/ivarref/aleph-encoding-problem
Removing a single char before the å character in the json files make the issue go away.

Thanks and best regards.

**Comment by ztellman** [comment]
`bs/to-string` assumes a UTF-8 encoding unless you specify otherwise using `(bs/to-string x {:encoding "a-different-encoding"})`.  JSON is required to be UTF-8 encoded, so this shouldn't be a problem, but it certainly resembles that sort of issue.  If you're certain this isn't the cause, I can take a closer look.

**Comment by ivarref** [comment]
Thanks. The file is properly UTF-8 encoded.

I've added code to verify this in the referred project:

```clojure
(test/is (str/includes? (slurp "bad.json") "sentralbyrå"))

(test/is (str/includes? (let [stream (io/input-stream (io/file "bad.json"))]
                          (bs/to-string stream))
                        "sentralbyrå"))
```

Both these pass, so the problem is not with the file.

**Comment by ztellman** [comment]
Okay, thanks.  I've been able to reproduce the issue locally, and it looks like this only happens when `raw-stream?` is true.  I'll need to dig into exactly why, but that should at least give you a workaround in the meantime.  Thanks for surfacing this issue.

**Comment by ztellman** [comment]
Okay, I seem to have narrowed down the issue to something unexpected.  This will not trigger the error:

```
curl -d @bad.json -H 'expect: ' localhost:8080 
```

The issue appears to be with the 100-continue functionality, and only in the "raw" handler.  I can't see any obvious issue there, and it's getting late, so I'll take a look tomorrow.

**Comment by ivarref** [comment]
Thanks.

Seems there is a special (optional) handler for this in Netty:
https://github.com/netty/netty/pull/6474

(I don't know enough about Netty/Aleph/HTTP to know if this is helpful, but anyway...)

**Comment by ztellman** [comment]
If you target the latest alpha release of byte-streams this should be fixed.  The expect-continue thing was a red herring, it just caused the chunks of the body to be split somewhere else, hiding the underlying issue.  Thank you again for bringing this to my attention.
