### ISSUE TITLE
browser request failed after enable :compression?

### ISSUE THREAD

**Issue by zerg000000** [ztellman/aleph#356]
a litte repl code to reproduce the case

assuming a text file abc.html at classpath `public/abc.html`

```
user=>(require '[ring.middleware.resource :as resource])
nil
user=>(require '[aleph.http :as http])
nil
user=>(def s (http/start-server (resource/wrap-resource identity "public/") 
  {:compression? true :port 3000}))
#'user/s
user=>(slurp (:body @(http/get "http://localhost:3000/abc.html")))
"<html>\n<head>\n  <link href=\"style.css\" rel=\"stylesheet\">\n</head>\n<body>\nHellll\n</body>\n</html>\n"
```

it works okay in `http/get`.

But when I try it in browser. it failed with status stalled.

the project.clj
```
(defproject aleph-is "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [ring "1.6.3"]
                 [aleph "0.4.5-alpha3"]])
```

The it is not working since 0.4.4 which first introduce the flag `:compression?`

**Comment by kachayev** [comment]
@zerg000000 Looks like there is a problem with how pipeline forks with files. The `HttpContentCompressor` expects `HttpContent` objects as input chunks to be compressed, that does not play nicely both with `HttpChunkedInput` and `DefaultFileRegion`. 

As a quick workaround, you can read a file in memory and set it to `:body` "manually" to avoid using `send-file-region` and `send-chunked-file`. For the more robust solution we need either to wrap `ChunkedInput` or subclass `HttpContentCompressor` (not to lose zero-copy capabilities of `FileRegion`). I need to check both solutions to have a better understanding of the trade-off.

**Comment by zerg000000** [comment]
Cool. Thanks for your in deep answer!

**Comment by kachayev** [comment]
@zerg000000 I opened a new PR with the solution for your problem, but you can actually do the same thing "manually" using optional `pipeline-transform` callback. Should look like this:

```clojure
(http/start-server handler
                   {:compression? true
                    :port 3000
                    :pipeline-transform #(doto % (.addAfter "deflater" "streamer" (ChunkedWriteHandler.)))})
```

**Comment by zerg000000** [comment]
Tested. work like a charm!

**Comment by kachayev** [comment]
@ztellman I think it's safe now to close this issue 🤔
