### ISSUE TITLE
:aleph/request-arrived is unreliable

### ISSUE THREAD

**Issue by greglook** [ztellman/aleph#361]
This took a while to puzzle out. 🕵️ 

The `:aleph/request-arrived` key (from #273 and #275) in the request map is defined [here](https://github.com/ztellman/aleph/blob/f4688f6024a5fc981f3eed112c4a962529dc5cfa/src/aleph/http/core.clj#L199). The fact that it is defined inside a [`def-derived-map`](https://github.com/ztellman/potemkin/blob/f1a13fd07e294413610a09d4eade92a46102bfa7/src/potemkin/collections.clj#L261) macro from potemkin means that the _value_ of the timestamp gets re-evaluated each time you access it. This makes it essentially useless for tracking the elapsed time of a specific request. 😢 

I've worked around this in the meantime by adding my own timestamp to the request, but it would be nice to be able to rely on the aleph key.

**Comment by ztellman** [comment]
I'm sorry I didn't catch this in the original PR, thanks for tracking down the issue.  I'll be cutting a new release in just a sec, so you shouldn't have to rely on your workaround.

**Comment by greglook** [comment]
Thanks for the quick fix!
