### ISSUE TITLE
Aleph has a corrupt repository

### ISSUE THREAD

**Issue by dakrone** [ztellman/aleph#368]
This might be too meta to be addressed, but with git's fsck checking, cloning aleph fails:

```
~/src/clj λ git clone git@github.com:ztellman/aleph.git
Cloning into 'aleph'...
remote: Counting objects: 8934, done.        
remote: Compressing objects: 100% (61/61), done.        
error: object 31dfaf308f5ea00c04c0653ecbe8937fb0add324: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

You can reproduce this by adding these to `~/.gitconfig`:

```
[transfer]
  fsckObjects = true
[fetch]
  fsckObjects = true
[receive]
  fsckObjects = true
```

And then cloning aleph.

**Comment by gsnewmark** [comment]
It was already reported :slightly_frowning_face:  https://github.com/ztellman/aleph/issues/327

**Comment by dakrone** [comment]
Ahh you're right, I'll close this since it is a duplicate then, thanks
