### ISSUE TITLE
aleph.http.core.NettyRequest - bug in c.l.IPersistentCollection.cons(Map) implementation

### ISSUE THREAD

**Issue by kumarshantanu** [ztellman/aleph#374]
(This might be related to Potemkin, I'm not sure.)

When I have a request of type `aleph.http.core.NettyRequest`, the call `(conj request {:foo 10})` does not merge the latter map into the request. Whereas, the call `(conj {:bar 20} {:foo 10})` merges the two maps into one.

**Comment by kachayev** [comment]
@kumarshantanu `conj` works by calling `cons` on the `IPersistentCollection` which is handled by the potermkin's `AbstractMap`. So... it should work 🤔 Would you please share the code that fails?

**Comment by kachayev** [comment]
Double checked

```clojure
user=> (import 'io.netty.handler.codec.http.DefaultFullHttpRequest)
io.netty.handler.codec.http.DefaultFullHttpRequest
user=> (import 'io.netty.handler.codec.http.HttpMethod)
io.netty.handler.codec.http.HttpMethod
user=> (import 'io.netty.handler.codec.http.HttpVersion)
io.netty.handler.codec.http.HttpVersion
user=> (require '[aleph.http.core :as c])
nil
user=> (def req (DefaultFullHttpRequest. HttpVersion/HTTP_1_
HttpVersion/HTTP_1_0          HttpVersion/HTTP_1_0_STRING   HttpVersion/HTTP_1_1
HttpVersion/HTTP_1_1_STRING
user=> (def req (DefaultFullHttpRequest. HttpVersion/HTTP_1_1
HttpVersion/HTTP_1_1          HttpVersion/HTTP_1_1_STRING
user=> (def req (DefaultFullHttpRequest. HttpVersion/HTTP_1_1 Http
HttpMethod    HttpVersion
user=> (def req (DefaultFullHttpRequest. HttpVersion/HTTP_1_1 HttpMethod/GET "https://google.com"))
#'user/req
user=> (def nr (c/netty-request->ring-request req false nil nil))
#'user/nr
user=> nr
{:aleph/request-arrived 3582944625596447, :aleph/keep-alive? true, :remote-addr nil, :headers {}, :server-port nil, :uri "https://google.com", :server-name nil, :query-string nil, :body nil, :scheme :http,:request-method :get}
user=> (class nr)
aleph.http.core.NettyRequest
user=> (conj nr {:foo :bar})
{:aleph/request-arrived 3582944625596447, :aleph/keep-alive? true, :remote-addr nil, :headers {}, :server-port nil, :foo :bar, :uri "https://google.com", :server-name nil, :query-string nil, :body nil, :scheme :http, :request-method :get}
```

As you can see, the result of `conj` contains `:foo` key.

**Comment by kumarshantanu** [comment]
@kachayev Thanks for providing a REPL script! My original bug report example was inaccurate, though the bug shows up when you use a `java.util.HashMap` instead of Clojure's persistent hashmap. For example, if you modify the last step as follows then the bug is evident:

```clojure
user=> (import 'java.util.HashMap)
java.util.HashMap
=> (conj nr (doto (HashMap.) (.put :foo :bar)))
{#object[java.util.HashMap$Node 0x59340f92 ":foo=:bar"] nil, :aleph/request-arrived 1217282039121021, :aleph/keep-alive? true, :remote-addr nil, :headers {}, :server-port nil, :uri "https://google.com", :server-name nil, :query-string nil, :body nil, :scheme :http, :request-method :get}
```

This discrepancy doesn't exist in Clojure's persistent map implementations.

**Comment by kachayev** [comment]
@kumarshantanu Ah, I see now. The problem is that `java.util.HashMap` does not implement `IPersistentMap` and `potemkin` does not have a special handling for this case in place (`clojure`'s `APersistentMap` [does](https://github.com/clojure/clojure/blob/ebfdbca535b81808b3ddc369d4a4e98b8f1524c7/src/jvm/clojure/lang/APersistentMap.java#L25)). 

Workaround here is pretty simple, 

```
(conj nr (into {} (doto (HashMap.) (.put :foo :bar))))
```

should work just fine. For the longer term, I will open a PR to handle this in `potemkin`'s `AbstractMap` implementation.

**Comment by kumarshantanu** [comment]
Just FYI, this issue is similar to https://issues.jboss.org/projects/IMMUTANT/issues/IMMUTANT-640 but not found with HTTP Kit or Ring-jetty-adapter.

**Comment by kachayev** [comment]
`Immutant` uses `potemkin` as well, so I think the root of the problem there is just the same.

**Comment by kachayev** [comment]
As far as `aleph` targets `potemkin` 0.4.5, this should be covered by https://github.com/ztellman/potemkin/commit/844f40392d5750ec3b2af424a70ab2e3fc4b8c5c
