### ISSUE TITLE
Override the Server header value

### ISSUE THREAD

**Issue by danjohansson** [ztellman/aleph#391]
I would like to be able to override the Server header value as a security measure.
Seems like there is no easy way for that currently?

**Comment by danielcompton** [comment]
I couldn't see an obvious way to do that, as the Server header is added after everything else. One possible way to do this would be to monkeypatch `aleph.http.server/send-response` to remove the Server header from being added:

```clj
(ns myapp.monkeypatching
  (:require [aleph.http.server]))

(in-ns 'aleph.http.server)

(let [[connection-name date-name]
      (map #(HttpHeaders/newEntity %) ["Connection" "Date"])

      [keep-alive-value close-value]
      (map #(HttpHeaders/newEntity %) ["Keep-Alive" "Close"])]
  (defn send-response
    [^ChannelHandlerContext ctx keep-alive? ssl? rsp]
    (let [[^HttpResponse rsp body]
          (try
            [(http/ring-response->netty-response rsp)
             (get rsp :body)]
            (catch Throwable e
              (let [rsp (error-response e)]
                [(http/ring-response->netty-response rsp)
                 (get rsp :body)])))]

      (netty/safe-execute ctx

        (doto (.headers rsp)
          (.set ^CharSequence connection-name (if keep-alive? keep-alive-value close-value))
          (.set ^CharSequence date-name (date-header-value ctx)))

        (http/send-message ctx keep-alive? ssl? rsp body)))))

(in-ns 'myapp.monkeypatching)
```

(Untested, but based on similar monkeypatching code I've done).

There is probably a better long-term solution though (maybe setting Properties or some other startup-time setting?)

**Comment by danielcompton** [comment]
Thanks @ztellman! The new approach now is to set your own Server header, and Aleph will detect that and not overwrite it.

**Comment by danjohansson** [comment]
@ztellman @danielcompton  Thanks! 👍

**Comment by OriginalFenno** [comment]
Hi! Hopeful first-time contributor - what about (start-server header {:hide-server-header? true}) to omit the header completely? I can't help but find adding (merge-with conj response {:headers {"Server" ""}}) as middleware an untidy solution.
