### ISSUE TITLE
Error when proxy port passed as string

### ISSUE THREAD

**Issue by smithtim** [ztellman/aleph#418]
In `proxy-options` for an HTTP `connection-pool`, when I pass the proxy port as a string, e.g. "3128", I get `java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Character`.  The exception is coming from `proxy-handler` in `client.clj`.  That function is calling `int` on the port, but I think `Integer/parseInt` is what you want to convert the port from a string.

**Comment by ztellman** [comment]
Ports are expected to be numbers in Aleph. The error message leaves
something to be desired, but this is not a bug.

**Comment by smithtim** [comment]
Hmm, then why do you call `int` on the port in `proxy-handler`?

Consider it a feature request ;)  To support both strings and numbers, or at least improve the error message.

Thanks!

**Comment by ztellman** [comment]
We call `int` to coerce numbers which aren't 32-bit integers to the correct primitive type, which helps us avoid any runtime reflection.  I don't think auto-coercion of strings into numbers is idiomatic within this library or within the Clojure ecosystem as a whole, but I'll give some thought on how to improve the error message.
