### ISSUE TITLE
Aleph HTTP server stops serving requests

### ISSUE THREAD

**Issue by ricardoekm** [ztellman/aleph#424]
We're replacing HTTP Kit by Aleph in an open source project ([restQL-core](https://github.com/B2W-BIT/restQL-server) and [restQL-server](https://github.com/B2W-BIT/restQL-server)) seeking performance and reliability improvements. 

We're facing an issue where after a high load Aleph HTTP server stops serving requests, even hours after the load stops. It gets stuck in 503 error 503 Service Unavailable, like there's no more executors available. The only way to fix it is to restart the java process.

Taking a thread dump, we've noticed that 2048 threads are stuck the following stack trace. 2048 is the max number of executors we're using. So indeed the pool is getting stucked and is being exhausted.

```
java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000071ff00198> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at manifold.deferred.Deferred.deref(deferred.clj:441)
        at clojure.core$deref.invokeStatic(core.clj:2228)
        at clojure.core$deref.invoke(core.clj:2214)
        at compojure.response$fn__233.invokeStatic(response.clj:51)
        at compojure.response$fn__233.invoke(response.clj:35)
        at compojure.response$fn__179$G__174__186.invoke(response.clj:7)
        at compojure.response$fn__229.invokeStatic(response.clj:47)
        at compojure.response$fn__229.invoke(response.clj:35)
        at compojure.response$fn__179$G__174__186.invoke(response.clj:7)
        at compojure.core$wrap_response$fn__622.invoke(core.clj:158)
        at compojure.core$wrap_route_middleware$fn__606.invoke(core.clj:128)
        at compojure.core$wrap_route_info$fn__611.invoke(core.clj:137)
        at compojure.core$wrap_route_matches$fn__615.invoke(core.clj:146)
        at compojure.core$routing$fn__630.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2592)
        at clojure.core$some.invoke(core.clj:2583)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at compojure.core$routes$fn__634.invoke(core.clj:192)
        at restql.server.exception_handler$wrap_exception_handling$fn__1266.invoke(exception_handler.clj:14)
```

The ring handler line hanging is [wrap_response(core.clj:158)](https://github.com/B2W-BIT/restQL-server/blob/master/src/restql/server/async_handler.clj#L213) which in turn invokes Compoure default routes handler. It seems to be waiting deref of manifold, which in turn is created by Aleph HTTP client.

Our interation with Aleph/Manifold is basic the below for the [server part](https://github.com/B2W-BIT/restQL-server/blob/master/src/restql/server/async_handler.clj):
```clojure
; Workaround Compojure thread blocking
(extend-protocol Renderable
  manifold.deferred.IDeferred
  (render [d _] d))
...
    (m-stream/take!
      (m-stream/->source
        (go
          (alt!
            result-ch ([result]
                        (log/debug {:time    (- (System/currentTimeMillis) time-before)
                                :success true}
                          "restQL Query finished")
                        result)
            error-ch ([err]
                        (log/error {:time    (- (System/currentTimeMillis) time-before)
                                :success false}
                          "restQL Query finished")
                        err)))))))
```

For the [client part]( 
https://github.com/B2W-BIT/restQL-core/blob/master/src/main/restql/core/async_request.clj#L191):
```clojure
        request-map     {:url                (:url request)
                          :request-method     (:http-method request)
                          :content-type       "application/json"
                          :resource           (:resource request)
                          :connection-timeout request-timeout
                          :request-timeout    request-timeout
                          :read-timeout       request-timeout
                          :query-params       (into (:query-params request) forward-params)
                          :headers            (:headers request)
                          :time               time-before
                          :body               (some-> request :post-body)
                          :pool               client-connection-pool
                          :pool-timeout       request-timeout}]
     (log/debug request-map "Preparing request")
     ; Before Request hook
     (hook/execute-hook query-opts :before-request request-map)
     (d/on-realized (http/request request-map)
                    #(request-respond-callback %
                                              :request request
                                              :request-timeout request-timeout
                                              :query-opts query-opts
                                              :time-before time-before
                                              :output-ch output-ch)
                    #(request-error-callback %
                                              :request request
                                              :request-timeout request-timeout
                                              :query-opts query-opts
                                              :time-before time-before
                                              :output-ch output-ch)))))
```

Given all timeouts are configured, there should be no reason for the deref be hanging forever. 

Any idea on what's might be going on or any troubleshooting tip?

Any help is appreciated. Thanks a lot!

**Comment by ricardoekm** [comment]
Full thread dump [dump.txt.zip](https://github.com/ztellman/aleph/files/2567864/dump.txt.zip)

**Comment by ricardoekm** [comment]
We've found some unhandled exceptions in the callback methods:

`2018-11-09 20:39:51,996 ERROR m.deferred [manifold-pool-1-200] error in deferred handler
java.lang.NullPointerException: null`

May an unhandled exception in the handler callback prevent the deref?

**Comment by ricardoekm** [comment]
We don't know why, but it seems log4j2 was screwing everything (despite it's not in the thread dump). We're testing with async logback, seems to solve the problem. 

We'll make more tests, if it's ok, will close the issue.

**Comment by ricardoekm** [comment]
Hi @ztellman, thank you very much for the help! 

We're using Compojure 1.6.1. Will try the suggested change.

**Comment by ricardoekm** [comment]
Maybe it's a corner case. The original extended-protocol made effect to some extend. These are our original tests with extend-protocol and without it. Now we're testing the extended-protocol adding   clojure.lang.IDeref.  

without-extended protocol
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 245
:num-workers 258
:num-workers 259
:num-workers 259
:num-workers 259
:num-workers 259
:num-workers 259
:num-workers 259
:num-workers 259
:num-workers 278
:num-workers 278
:num-workers 259
:num-workers 243
:num-workers 228
:num-workers 214
:num-workers 202
:num-workers 189
:num-workers 175
:num-workers 247
:num-workers 260
:num-workers 259
:num-workers 258
:num-workers 257
:num-workers 256
:num-workers 255
:num-workers 254
:num-workers 253
:num-workers 263
:num-workers 262
:num-workers 258
:num-workers 254
:num-workers 250
:num-workers 246
:num-workers 243

with simple extend-protocol
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 1
:num-workers 56
:num-workers 58
:num-workers 43
:num-workers 32
:num-workers 24
:num-workers 18
:num-workers 13
:num-workers 9
:num-workers 6
:num-workers 71
:num-workers 69
:num-workers 51
:num-workers 38
:num-workers 28
:num-workers 21
:num-workers 15
:num-workers 11
:num-workers 8
:num-workers 41
:num-workers 35
:num-workers 26
:num-workers 19
:num-workers 14
:num-workers 10

**Comment by ztellman** [comment]
The concrete deferred types inherit from both `IDeferred` and `IDeref`, so I think it may be non-deterministic which one is chosen.  Thanks for surfacing this issue, I'll update the example code accordingly.

**Comment by ricardoekm** [comment]
It did the trick! Thanks!!!
