### ISSUE TITLE
for some requests aleph HTTP client prepends invalid bytes to response

### ISSUE THREAD

**Issue by k7d** [ztellman/aleph#435]
example - this is PNG and the correct response starts with -119 80...:
```clojure
(->> @(http/get "https://whimsical.co/s/images/favicon-96.png?v=e6206c6071d5442388b98afe4b3f4c18")
     :body
     bs/to-byte-array
     (take 20))
=> (-119 80 78 71 13 10 26 10 0 0 0 13 73 72 68 82 0 0 0 96)
(->> @(http/get "https://whimsical.co/s/images/favicon-96.png?v=e6206c6071d5442388b98afe4b3f4c18")
     :body
     bs/to-byte-array
     (take 20))
=> (31 -117 8 0 0 0 0 0 0 0 0 0 32 -1 -33 -119 80 78 71 13)
(->> @(http/get "https://whimsical.co/s/images/favicon-96.png?v=e6206c6071d5442388b98afe4b3f4c18")
     :body
     bs/to-byte-array
     (take 20))
=> (-119 80 78 71 13 10 26 10 0 0 0 13 73 72 68 82 0 0 0 96)
(->> @(http/get "https://whimsical.co/s/images/favicon-96.png?v=e6206c6071d5442388b98afe4b3f4c18")
     :body
     bs/to-byte-array
     (take 20))
=> (31 -117 8 0 0 0 0 0 0 0 0 0 32 -1 -33 -119 80 78 71 13)
```

**Comment by k7d** [comment]
Oddly it only happens when query attribute is specified. `https://whimsical.co/s/images/favicon-96.png` works fine all the time.

**Comment by kachayev** [comment]
@k7d I've tried to perform your request a few times using `curl`. The server actually replies with different responses: once gzipped, once not. Seems like randomly. Maybe there are a few servers under the load balancer or something. Are you sure that the response *should* be the same each time?

**Comment by kachayev** [comment]
Right, you can adjust this using `pipeline-transform` option. Not sure why it's not included by default. For a server, we have `:compression?` option to include deflator. I don't see any drawbacks not to include this for client pipeline tho'. The only one potential objection: it might break the code if I already use `pipeline-transform` that adds a decompressor. @ztellman What do you think?

**Comment by kachayev** [comment]
@k7d BTW, you didn't specify `Accept-Encoding` header, so sending gzipped content is in fact a server failure :) 

I've checked `clj-http` documentation. It says

> The client transparently accepts and decompresses the gzip and deflate content encodings.

It also provides `:decompress-body?` [option](https://github.com/dakrone/clj-http#decompression) to switch off `Accept-Encoding` headers and body decompression on detected `Content-Encoding`. By default, this option is set to `true`. If we want to provide the same API, we need to cover those case as well. But once again, we cannot just start including `Accept-Encoding: gzip, deflate` to any request as it's definitely would be a breaking change for a lot of users. But we can do the following: introduce `:decompress-body?` option set to `false` by default, when set to `true` explicitly using `connection-options`, - add decompressor and appropriate header. I'll make a PR if there are no objections, @ztellman.

**Comment by kachayev** [comment]
@k7d If you have no objections, I would close this issue and open another one with a feature request for automatic body decompression on a client side (just not to confuse anyone).

**Comment by kachayev** [comment]
https://github.com/ztellman/aleph/issues/444
