### ISSUE TITLE
Use volatiles instead of atoms to store intermediate state in handlers

### ISSUE THREAD

**Issue by kachayev** [ztellman/aleph#451]
We use a bunch of atoms to store intermediate state to implement both `ring-handler` and `raw-ring-handler` (e.g. [here](https://github.com/ztellman/aleph/blob/be1ee04c130660ce69ee7c6603132b36be79ec1f/src/aleph/http/server.clj#L224-L227)). It seems like the state is encapsulated in a way that access is sequential. We also don't use any fancy features of atoms, like watchers or compare-and-swap. So, I think, volatile variables would be sufficient to cover the functionality.

**Comment by alexander-yakushev** [comment]
I've never seen anything atom-related showing up in the profile, so I don't think this would give any visible improvement.

**Comment by kachayev** [comment]
@alexander-yakushev Well... most probably it would not, comparing to other parts of the handler. But it's the same story as we had in #378: when you can do less work, you most certainly should.
