### ISSUE TITLE
Question: why some I/O of HTTP client happens on the caller thread?

### ISSUE THREAD

**Issue by alexander-yakushev** [ztellman/aleph#463]
Couldn't find the answer anywhere on the Internet, so might as well ask here.

When profiling an Aleph-powered program, I noticed that some I/O work happens on the calling thread rather than on a Netty thread. It's relatively small part the profile, but I'm apprehensive that it might be blocking and adding latency to the caller thread. Here's how the profile of the caller thread looks like:

<img width="1192" alt="screen shot 2019-01-17 at 17 05 48" src="https://user-images.githubusercontent.com/468477/51327783-ba926780-1a7a-11e9-8de5-6c5c97e527bc.png">

<p align="center"><i>Observe __write.</i></p>

I've tracked this down to [this code](https://github.com/ztellman/aleph/blob/master/src/aleph/http/client.clj#L540-L541.). The code schedules sending the content on the Netty event loop (by doing `netty/safe-execute`). From what I can tell, `send-message` really happens on the Netty thread, as evidenced by the profile of a Netty thread:

<img width="1186" alt="screen shot 2019-01-17 at 17 06 33" src="https://user-images.githubusercontent.com/468477/51327961-07763e00-1a7b-11e9-8b9e-0af01cb7409b.png">

<p align="center"><i>send-message happens here as expected.</i></p>

So, it appears that while most of the I/O work does happen on Netty threads, some work "leaks" onto the caller thread. It looks like when the caller calls `.execute` on the Netty's event loop it transitively runs `EpollArrayWrapper.interrupt` which in turn calls `__write`.

Is this something expected and benign, or should I worry?

**Comment by kachayev** [comment]
Does it happen using NIO instead of Epoll?

**Comment by alexander-yakushev** [comment]
Haven't tried yet, I'll get back when I have the results.

Meanwhile, I've found the code behind `interrupt` native function: https://github.com/frohoff/jdk8u-jdk/blob/master/src/solaris/native/sun/nio/ch/EPollArrayWrapper.c#L153. It looks like it tries to write a single byte to a file descriptor, possibly to wake up the thread in that EventExecutor. I'm trying to dig further to understand if that EventExecutor only listens to EPoll events, so that is the only way to wake it up.

**Comment by alexander-yakushev** [comment]
Poked around Netty's codebase and bug tracker a bit more. Yes, this is just me being stupid. `wakeup` writes to a pipe (hence, `pipe_write` function call) on the caller thread to trigger EventLoop's thread wakeup; for I/O the function is `tcp_sendmsg`.

eBPF shows that `pipe_write` doesn't take significant time:
![image](https://user-images.githubusercontent.com/468477/51340708-4cf53400-1a98-11e9-92be-09119fa5e280.png)
