### ISSUE TITLE
Close websocket connection with custom code and reason text

### ISSUE THREAD

**Issue by kachayev** [ztellman/aleph#470]
Right now both server and client connection send `CloseWebSocketFrame` with default status code and empty reason text when the appropriate stream is drained. I think we can add `websocket-close!` (analog with `websocket-ping`) helper to take care of the closing handshake and cleanup stream & connection after that. So it will look like

```clojure
(def conn <...>)
;; returns deferred that yields when connection is closed
(http/websocket-close! conn 4009 "Idle timeout, sorry (send more pings next time)")
```

**Comment by ztellman** [comment]
What does the `4009` represent here?

**Comment by kachayev** [comment]
Application-level status code (range 4000-4999), just randomly picked up one. Here's the full list of codes from [rfc6455](https://tools.ietf.org/html/rfc6455#section-7.4)

**Comment by kachayev** [comment]
I would say we need all 3 options:

```clojure
(websocket-close! conn)
(websocket-close! conn status-code)
(websocket-close! conn status-code reason)
```

Defaults are well defined, so it's clear what to use instead of missing params.

**Comment by ztellman** [comment]
Okay, works for me.

**Comment by kachayev** [comment]
@ztellman This functionality clashes with https://github.com/ztellman/aleph/pull/422 pretty heavily, so I'll make a new PR after that one is merged, so I can work around merge issue beforehand.

**Comment by kachayev** [comment]
Covered by #481.
