### ISSUE TITLE
as json is not decoded on 4xx

### ISSUE THREAD

**Issue by greut** [ztellman/aleph#492]
```clj
=> @(d/chain (aleph.http/get "https://httpstat.us/200"
                             {:as :json
                              :headers {:accept "application/json"}
                              :throw-exceptions false})
             :body)
"200 OK"

=> @(d/chain (aleph.http/get "https://httpstat.us/400"
                             {:as :json
                              :headers {:accept "application/json"}
                              :throw-exceptions false})
             :body)
"\"400 Bad Request\""
```

The later should be `"400 Bad Request"`

**Comment by greut** [comment]
Reading the code gave the answer, cheers.

```clj
=> @(d/chain (aleph.http/get "https://httpstat.us/400"
                             {:as :json
                              :coerce :always
                              :headers {:accept "application/json"}
                              :throw-exceptions false})
             :body)
"400 Bad Request"
```

**Comment by kachayev** [comment]
@greut Right, the fact is mentioned [here](https://github.com/dakrone/clj-http#output-coercion)

>>> JSON coercion defaults to only an “unexceptional” statuses, meaning status codes in the #{200 201 202 203 204 205 206 207 300 301 302 303 304 307} range. If you would like to change this, you can send the :coerce option, which can be set to:

:always        ;; always json decode the body
:unexceptional ;; only json decode when not an HTTP error response
:exceptional   ;; only json decode when it IS an HTTP error response
The :coerce setting defaults to :unexceptional.
